### ISSUE TITLE
[Android] Application crashes when initialization fails

### ISSUE THREAD

**Issue by iassal** [mogol/flutter_secure_storage#144]
When `onDetachedFromEngine` gets triggered, if for any reason, channel was null, the app crashes.

**Comment by iassal** [comment]
Sample Stack trace
```java 
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {REDACTED}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3869)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3887)
       at android.app.ActivityThread.access$1500(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)```
