### ISSUE TITLE
[Android] Apps can't open after update security path on android device 

### ISSUE THREAD

**Issue by ryanadit** [mogol/flutter_secure_storage#157]
Hi, i have some problem,
Sample stack tree in below

Debug service listening on ws://127.0.0.1:45545/K3kip_LWVJU=/ws
Syncing files to device SM A505F...
D/CertificatePolicyCache(23188): Creating new instance of CertificatePolicyCache myUid: 10727 callingUid: 10727
D/CertificatePolicyCache(23188): readVariables type: null userId: 0
E/StorageCipher18Impl(23188): unwrap key failed
E/StorageCipher18Impl(23188): java.security.InvalidKeyException: Failed to unwrap key
E/StorageCipher18Impl(23188): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:682)
E/StorageCipher18Impl(23188): 	at javax.crypto.Cipher.unwrap(Cipher.java:2440)
E/StorageCipher18Impl(23188): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.unwrap(RSACipher18Implementation.java:49)
E/StorageCipher18Impl(23188): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:44)
E/StorageCipher18Impl(23188): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.initInstance(FlutterSecureStoragePlugin.java:45)
E/StorageCipher18Impl(23188): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.onAttachedToEngine(FlutterSecureStoragePlugin.java:56)
E/StorageCipher18Impl(23188): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:133)
E/StorageCipher18Impl(23188): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
E/StorageCipher18Impl(23188): 	at java.lang.reflect.Method.invoke(Native Method)
E/StorageCipher18Impl(23188): 	at io.flutter.embedding.android.FlutterActivity.registerPlugins(FlutterActivity.java:972)
E/StorageCipher18Impl(23188): 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:873)
E/StorageCipher18Impl(23188): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:178)
E/StorageCipher18Impl(23188): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
E/StorageCipher18Impl(23188): 	at android.app.Activity.performCreate(Activity.java:7955)
E/StorageCipher18Impl(23188): 	at android.app.Activity.performCreate(Activity.java:7944)
E/StorageCipher18Impl(23188): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
E/StorageCipher18Impl(23188): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
E/StorageCipher18Impl(23188): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
E/StorageCipher18Impl(23188): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/StorageCipher18Impl(23188): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/StorageCipher18Impl(23188): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/StorageCipher18Impl(23188): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
E/StorageCipher18Impl(23188): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/StorageCipher18Impl(23188): 	at android.os.Looper.loop(Looper.java:237)
E/StorageCipher18Impl(23188): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/StorageCipher18Impl(23188): 	at java.lang.reflect.Method.invoke(Native Method)
E/StorageCipher18Impl(23188): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/StorageCipher18Impl(23188): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/StorageCipher18Impl(23188): Caused by: javax.crypto.IllegalBlockSizeException
E/StorageCipher18Impl(23188): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
E/StorageCipher18Impl(23188): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:680)
E/StorageCipher18Impl(23188): 	... 27 more
E/StorageCipher18Impl(23188): Caused by: android.security.KeyStoreException: Unknown error
E/StorageCipher18Impl(23188): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1550)
E/StorageCipher18Impl(23188): 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
E/StorageCipher18Impl(23188): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
E/StorageCipher18Impl(23188): 	... 28 more

if restart run

Syncing files to device SM A505F...
Restarted application in 2,243ms.
D/ViewRootImpl@8a462ea[MainActivity](23188): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=14 res=0x40001 s={true 531197280256} ch=false
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): Failed to handle method call
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): java.lang.IllegalArgumentException: Unsupported value: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:278)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:69)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:236)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.onMethodCall(FlutterSecureStoragePlugin.java:108)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at android.os.Looper.loop(Looper.java:197)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage(23188): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/flutter (23188): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unsupported value: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, null)
E/flutter (23188): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (23188): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (23188): <asynchronous suspension>
E/flutter (23188): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (23188): #3      FlutterSecureStorage.readAll (package:flutter_secure_storage/flutter_secure_storage.dart:49:40)
E/flutter (23188): #4      _SplashPageState._readSession (package:bukudigitalku/pages/splash_page.dart:32:31)
E/flutter (23188): #5      _SplashPageState.initState.<anonymous closure> (package:bukudigitalku/pages/splash_page.dart:22:7)
E/flutter (23188): #6      new Future.delayed.<anonymous closure> (dart:async/future.dart:318:39)
E/flutter (23188): #7      _rootRun (dart:async/zone.dart:1180:38)
E/flutter (23188): #8      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23188): #9      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (23188): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (23188): #11     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23188): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23188): #13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (23188): #14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (23188): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (23188): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (23188): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (23188):

**Comment by ryanadit** [comment]
keep read this guide 
https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup
