### ISSUE TITLE
WRONG_FINAL_BLOCK_LENGTH

### ISSUE THREAD

**Issue by spiritinlife** [mogol/flutter_secure_storage#163]
@mogol We are encountering this error on production, but unfortunately i am not able to reproduce it.

```
javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:602)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:365)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(Unknown Source:32)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$400(Unknown Source:11)
                                                                  access$500
                                                                  decodeRawValue
                                                                  ensureInitStorageCipher
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(Unknown Source:7)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(Unknown Source:0)
                                                                  access$100
                                                                  access$200
                                                                  access$300
                                                                  addPrefixToKey
                                                                  deleteAll
                                                                  getKeyFromCall
                                                                  initInstance
                                                                  write
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(Unknown Source:134)
	at java.lang.Thread.run(Thread.java:929)
```

What relevant information would you like me to include?

**Comment by danielFloat** [comment]
I'm having the same error on production.

**Comment by Omrankabalan** [comment]
Same here
Error is happening  on Samsung Android 10

`Non-fatal Exception: java.lang.Exception: PlatformException(Exception encountered, read, javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:602)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:365)
	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
	at c.e.a.b.b.b(StorageCipher18Implementation.java:7)
	at c.e.a.a.b(FlutterSecureStoragePlugin.java:12)
	at c.e.a.a.d(FlutterSecureStoragePlugin.java:2)
	at c.e.a.a.a(FlutterSecureStoragePlugin.java:4)
	at c.e.a.a$b.run(FlutterSecureStoragePlugin.java:12)
	at java.lang.Thread.run(Thread.java:919)
)`

**Comment by mogol** [comment]
Any luck to reproduce on a device or emulator? 

@spiritinlife when did you start receiving the errors? which version of plugin?

**Comment by danielFloat** [comment]
I switched the library from v3.3.4 to v3.3.3 and it stopped happening.

**Comment by spiritinlife** [comment]
@mogol I wasn't able to reproduce it. 

It started happening on 3.3.4. From then i have completed removed the library.

Some googling indicated that there could  some issue with the padding of values before encoding? i am not familiar with the android keystore though.

Something to consider maybe is to use this https://developer.android.com/topic/security/data-android-versions which would be hopefully be more stable. The only downside is that they api version support is 21+

**Comment by koskimas** [comment]
@spiritinlife This is likely also caused by the thread safety issues in the android code. See #161 for a reproduction and a workaround.
