### ISSUE TITLE
StorageCipher initialization failed on API 27

### ISSUE THREAD

**Issue by simonvaros** [mogol/flutter_secure_storage#175]
Hello, I recently upgraded my flutter app to android embedding v2, so I could update some of my packages. One of the packages was also Flutter secure storage and after this upgrade, everything runs fine (iOS, Android) except Android Emulator API 27 where I get following error when starting app. FlutterSecureStorage doesnt load, so many stuff in my app doesnt work, as it relies on this package.

Flutter version: 1.22.1
FlutterSecureStorage version: 3.3.5

My error:
```
E/FlutterSecureStoragePl( 8556): StorageCipher initialization failed
E/FlutterSecureStoragePl( 8556): java.security.UnrecoverableKeyException: Failed to obtain information about private key
E/FlutterSecureStoragePl( 8556): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:223)
E/FlutterSecureStoragePl( 8556): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
E/FlutterSecureStoragePl( 8556): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePrivateKeyFromKeystore(AndroidKeyStoreProvider.java:269)
E/FlutterSecureStoragePl( 8556): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:94)
E/FlutterSecureStoragePl( 8556): 	at java.security.KeyStore.getKey(KeyStore.java:1062)
E/FlutterSecureStoragePl( 8556): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:118)
E/FlutterSecureStoragePl( 8556): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:38)
E/FlutterSecureStoragePl( 8556): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
E/FlutterSecureStoragePl( 8556): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:72)
E/FlutterSecureStoragePl( 8556): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(FlutterSecureStoragePlugin.java:30)
E/FlutterSecureStoragePl( 8556): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:182)
E/FlutterSecureStoragePl( 8556): 	at android.os.Handler.handleCallback(Handler.java:790)
E/FlutterSecureStoragePl( 8556): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/FlutterSecureStoragePl( 8556): 	at android.os.Looper.loop(Looper.java:164)
E/FlutterSecureStoragePl( 8556): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/FlutterSecureStoragePl( 8556): Caused by: android.security.KeyStoreException: Invalid key blob
E/FlutterSecureStoragePl( 8556): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
E/FlutterSecureStoragePl( 8556): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:224)
E/FlutterSecureStoragePl( 8556): 	... 14 more
```

My flutter doctor

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/simonvaros/Development/flutter
    • Framework revision f30b7f4db9 (3 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/simonvaros/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by haydgately** [comment]
Same for me too!

**Comment by Adidi** [comment]
Me too - is there a fix for that ?

**Comment by berdroid** [comment]
Same problem here after upgrading to Android embedding V2.


[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on Linux, locale de_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)

Running on emulator with Android 8.1/API 27

**Comment by berdroid** [comment]
With the same setup as above, problem does not show on Android Oreo 10.0 API 29

**Comment by berdroid** [comment]
Just found out that failure goes away after deinstalling my app. Possible this clears any previous keys and the failure does not occur next time.

According to documentation, `UnrecoverableKeyException` from [`getKey`](https://developer.android.com/reference/java/security/KeyStore#getKey(java.lang.String,%20char[])) indicates that the key was present but could no be recovered, e.g. due to wrong password.

**Comment by rmControls** [comment]
I am also facing same issue....

If you clear app data manually you will see this error...

any fix for it??

**Comment by FernandoSini** [comment]
I'm currently facing this issue.
Does anyone has a fix for this?

**Comment by fundup** [comment]
Same problem here using 4.2.0. 
I have to wipe data and start emulator again.

**Comment by juliansteenbakker** [comment]
Can someone please confirm this is still happening with version 4.2.0 on a real device?

**Comment by fzyzcjy** [comment]
@juliansteenbakker Seems that @fundup reports error with 4.2.0

**Comment by juliansteenbakker** [comment]
With #270 you can now use the following code to enable EncryptedSharedPreferences:

```dart
  AndroidOptions _getAndroidOptions() => const AndroidOptions(
        encryptedSharedPreferences: true,
      );
```

This method doesn't use the custom StorageCipher but rather a Jetpack Compose library that automatically encrypts the data. Please note that on API < 23 it will fall back to the 'regular' secure storage.

**Comment by alexrvarela** [comment]
If you send any options, (Ex. `encryptedSharedPreferences: true` in Android) StorageCipher18Implementation is always initialized regardless of whether it is needed or not:

`        if (options != null) {
            useEncryptedSharedPreferences = useEncryptedSharedPreferences(options);
            resetOnError = resetOnError(options);

            if (storageCipher == null) {
                try {
                    storageCipher = new StorageCipher18Implementation(applicationContext);
                } catch (Exception e) {
                    Log.e(TAG, "StorageCipher initialization failed", e);
                }
            }
`
