### ISSUE TITLE
Secure Storage was working but now Null Pointer-ing

### ISSUE THREAD

**Issue by haydgately** [mogol/flutter_secure_storage#190]
Hi, 

I had flutter storage working seamlessly. I then did a fix for my app and updated the build number and released a new version, but now the app open and stays on a black screen. When I looked in the logs, it fails when trying to read or readAll from the Secure Storage: 

`java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.it_nomads.fluttersecurestorage.ciphers.StorageCipher.decrypt(byte[])' on a null object reference
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:162)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.readAll(FlutterSecureStoragePlugin.java:118)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$400(FlutterSecureStoragePlugin.java:30)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:201)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
`

Does anyone else have this issue? Thanks

**Comment by moms-spaghetti** [comment]
Yep I have this. Have you had any progress on a fix?

**Comment by moms-spaghetti** [comment]
Bizarrely managed to fix my issue just after I made my last comment. I had a dependancy of `flutter_secure_storage: ^3.3.5`. I increased to `flutter_secure_storage: ^4.0.0` and no longer get the error.

**Comment by juliansteenbakker** [comment]
Please try again using the latest version. If you still encounter this issue feel free to comment and I'll reopen this.
