### ISSUE TITLE
intermittent failures to register plugin on Android emulator

### ISSUE THREAD

**Issue by stevesea** [mogol/flutter_secure_storage#20]
Intermittently, I'll get the following error trying to start my app on an Android emulator (nexus 6 api 27, android 8.1 (google apis)

```

Built build/app/outputs/apk/debug/app-debug.apk.
E/FlutterSecureStoragePl( 6890): Registration failed
E/FlutterSecureStoragePl( 6890): java.security.UnrecoverableKeyException: Failed to obtain information about private key
E/FlutterSecureStoragePl( 6890): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:223)
E/FlutterSecureStoragePl( 6890): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
E/FlutterSecureStoragePl( 6890): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePrivateKeyFromKeystore(AndroidKeyStoreProvider.java:269)
E/FlutterSecureStoragePl( 6890): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:94)
E/FlutterSecureStoragePl( 6890): 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:482)
E/FlutterSecureStoragePl( 6890): 	at java.security.KeyStore.getEntry(KeyStore.java:1560)
E/FlutterSecureStoragePl( 6890): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:93)
E/FlutterSecureStoragePl( 6890): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:30)
E/FlutterSecureStoragePl( 6890): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:30)
E/FlutterSecureStoragePl( 6890): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.<init>(FlutterSecureStoragePlugin.java:46)
E/FlutterSecureStoragePl( 6890): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(FlutterSecureStoragePlugin.java:33)
E/FlutterSecureStoragePl( 6890): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:28)
E/FlutterSecureStoragePl( 6890): 	at [...myapplication...].MainActivity.onCreate(MainActivity.java:11)
E/FlutterSecureStoragePl( 6890): 	at android.app.Activity.performCreate(Activity.java:7009)
E/FlutterSecureStoragePl( 6890): 	at android.app.Activity.performCreate(Activity.java:7000)
E/FlutterSecureStoragePl( 6890): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
E/FlutterSecureStoragePl( 6890): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
E/FlutterSecureStoragePl( 6890): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
E/FlutterSecureStoragePl( 6890): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/FlutterSecureStoragePl( 6890): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
E/FlutterSecureStoragePl( 6890): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterSecureStoragePl( 6890): 	at android.os.Looper.loop(Looper.java:164)
E/FlutterSecureStoragePl( 6890): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/FlutterSecureStoragePl( 6890): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterSecureStoragePl( 6890): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/FlutterSecureStoragePl( 6890): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/FlutterSecureStoragePl( 6890): Caused by: android.security.KeyStoreException: Invalid key blob
E/FlutterSecureStoragePl( 6890): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
E/FlutterSecureStoragePl( 6890): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:224)
E/FlutterSecureStoragePl( 6890): 	... 25 more
Syncing files to device Android SDK built for x86...
```

Flutter doctor output: 
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
[✓] VS Code (version 1.27.1)
[✓] Connected devices (2 available)

• No issues found!
```

To get the application to run again, I have to wipe the emulator's data with AVD.

This seems more likely to happen if I've left my emulator running overnight or let my laptop go to sleep. But, I'm not 100% sure of the correlation.

**Comment by mogol** [comment]
Please check 
https://github.com/mogol/flutter_secure_storage/issues/13#issuecomment-421548426

**Comment by stevesea** [comment]
upgraded to 3.1.2, seems to be behaving better;  I still see that stack trace occasionally, but the app is still functional -- so it must be recovering from the problem

in case it's interesting, here's the current stack trace :
```
16:48:40.702 10 info flutter.tools Built build/app/outputs/apk/debug/app-debug.apk.
16:48:41.365 11 info flutter.tools E/FlutterSecureStoragePl( 8682): Registration failed
16:48:41.365 12 info flutter.tools E/FlutterSecureStoragePl( 8682): java.security.UnrecoverableKeyException: Failed to obtain information about private key
16:48:41.365 13 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:223)
16:48:41.365 14 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
16:48:41.365 15 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePrivateKeyFromKeystore(AndroidKeyStoreProvider.java:269)
16:48:41.365 16 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:94)
16:48:41.365 17 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:482)
16:48:41.365 18 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at java.security.KeyStore.getEntry(KeyStore.java:1560)
16:48:41.365 19 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:93)
16:48:41.365 20 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:30)
16:48:41.365 21 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
16:48:41.365 22 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.<init>(FlutterSecureStoragePlugin.java:46)
16:48:41.365 23 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(FlutterSecureStoragePlugin.java:33)
16:48:41.365 24 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:28)
16:48:41.365 25 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at [classpathredacted].MainActivity.onCreate(MainActivity.java:11)
16:48:41.365 26 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.app.Activity.performCreate(Activity.java:7009)
16:48:41.365 27 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.app.Activity.performCreate(Activity.java:7000)
16:48:41.365 28 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
16:48:41.365 29 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
16:48:41.365 30 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
16:48:41.365 31 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
16:48:41.365 32 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
16:48:41.365 33 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.os.Handler.dispatchMessage(Handler.java:106)
16:48:41.365 34 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.os.Looper.loop(Looper.java:164)
16:48:41.365 35 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
16:48:41.365 36 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at java.lang.reflect.Method.invoke(Native Method)
16:48:41.365 37 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
16:48:41.365 38 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
16:48:41.365 39 info flutter.tools E/FlutterSecureStoragePl( 8682): Caused by: android.security.KeyStoreException: Invalid key blob
16:48:41.365 40 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
16:48:41.365 41 info flutter.tools E/FlutterSecureStoragePl( 8682): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:224)
16:48:41.365 42 info flutter.tools E/FlutterSecureStoragePl( 8682): 	... 25 more
16:48:42.253 43 info flutter.tools Syncing files to device Android SDK built for x86...
```

**Comment by mogol** [comment]
@stevesea thanks for confirmation!
Sorry for inconvenience caused
