### ISSUE TITLE
Getting Platform Exception on writing data after updating the app

### ISSUE THREAD

**Issue by Sujal1** [mogol/flutter_secure_storage#200]
I am storing values (such as tokens) on user login, using this library. While testing in devices, it's working fine. However, I am facing an issue when the app gets updated. The error log I have traced is as follows:

**PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] c.g.a.b.c.a(byte[])' on a null object reference
	at c.g.a.a.a(Unknown Source:8)
	at c.g.a.a.a(Unknown Source:0)
	at c.g.a.a$b.run(Unknown Source:165)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:192)
	at android.os.HandlerThread.run(HandlerThread.java:65)
, null)**

And according to the logs so far, this issue is occuring in certain android devices.

I am using version 3.3.3 of the library, and following is the flutter doctor summary screenshot.

<img width="616" alt="Screen Shot 2021-01-22 at 17 03 26" src="https://user-images.githubusercontent.com/6914866/105697638-e6c80500-5f2c-11eb-95ed-45244b0f0f22.png">

How can this problem be solved?

**Comment by Sujal1** [comment]
Any way to resolve this, @mogol and team ? I am having difficulty to figure it out as in order to replicate this, I need to make a release on play store.

**Comment by pamir72** [comment]
I got this exception 2 days ago  after upgrade Redmi Note 8 Pro to Android 11 (MUI 12.5.1)

flutter_secure_storage: ^4.2.0

[✓] Flutter (Channel dev, 2.4.0-4.0.pre, on macOS 11.4 20F71 darwin-x64, locale ru-RU)
    • Flutter version 2.4.0-4.0.pre at /Users/xxxxxxx/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (2 weeks ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pavelmiheev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.164

**Comment by juliansteenbakker** [comment]
While searching for solutions i stumbled across this answer: https://stackoverflow.com/a/51166728

Did any of you alter something in the manifest? If so, this could be the problem.

**Comment by juliansteenbakker** [comment]
I'm closing this for now due to no activity. If anyone still has this issue, feel free to comment.

**Comment by Sujal1** [comment]
My manifest file looks like this:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package=“xxx.xxx.xxx”>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />

    <application
        android:allowBackup="false"
        android:name="io.flutter.app.FlutterApplication"
        android:icon="@mipmap/ic_launcher"
        android:label=“xxx”>
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

        </activity>
        
           <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

and there is no any change in this file during my app releases. Is there anything specific here in this manifest file that might have been triggering this exception? 

Also, the stackoverflow question above mentions about the shared preference being cleared out so i am not sure if that is related to this exception being generated @juliansteenbakker

**Comment by juliansteenbakker** [comment]
That seems fine to me. On which devices do you see this error? What android versions are they running? And are you using the latest version of this package?

**Comment by Sujal1** [comment]
i have received this in Redmi note 4, mi a2 lite, some Samsung versions like J400F, A505FN etc with different android versions ranging from 7.0 t0 9.0

the package version is 3.3.3 in my pubspec.yaml file

`flutter_secure_storage: ^3.3.3`

in pubspec.lock file, the version is 3.3.5 

```
 flutter_secure_storage:
    dependency: "direct main"
    description:
      name: flutter_secure_storage
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.3.5"
```

**Comment by juliansteenbakker** [comment]
Can you first try upgrading to the latest version, v4.2.1. There are numerous changes which may solve your problem.

v4.0.0 is null-safety so if your project isn't i suggest upgrading first since no updates are made for non-null satefy.

**Comment by David-Mou** [comment]
I'm receiving this error stack from one of my clients. I'm not able to reproduce it in my devices:

```
PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] c.g.a.b.c.a(byte[])' on a null object reference
	at c.g.a.a.a(FlutterSecureStoragePlugin.java:21)
	at c.g.a.a.a(FlutterSecureStoragePlugin.java:3)
	at c.g.a.a$b.run(FlutterSecureStoragePlugin.java:21)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null)
```

The device is: **Redmi Note 8 Pro** with Android 11
flutter_secure_storage version used: **4.2.0**

It's me or this looks as this issue is happening in Redmi devices?

**Comment by David-Mou** [comment]
I have 65 issues in my error monitoring system regarding this issue. All users affected have the Redmi Note 8 Pro with Android 11.

**Comment by David-Mou** [comment]
More research here: With **Redmi Note 8 Pro** and **Android 10**, this is not happening. This same device updated to **Android 11**, it's failing.

Model version of the devices with the issue: **RP1A.200720.011**

**Comment by juliansteenbakker** [comment]
May be related to #152.

> All users affected have the Redmi Note 8 Pro with Android 11.

It seems like some devices are affected by this issue. Since i don't encounter this issue i can't debug it. You should upload the code symbols to the play store. That way you can unminify the code and see the full stacktrace. There isn't a lot i can do now because i really don't know what may cause this issue.

**Comment by eliasjtg** [comment]
Same issue in moto g7 plus (Android 10)

**Comment by erdemyerebasmaz** [comment]
Hi there,
One of our users encountered this issue on a **Redmi Note 8 Pro** with **Android 11** on our app that's released on **Google Play Store**. Except it happened on **read** instead of write operation but I suspect the root error is the same so I didn't see the need to open a new issue.
We're currently using flutter_secure_storage version **4.2.0**, our app uses **embedding v2** and there has been no changes to our **AndroidManifest.xml** file in a long while. 

Let me know if you require more information.
<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-GB)
    • Flutter version 2.2.3 at C:\Dev\sdk\flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Dev\sdk\Android\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Dev\sdk\Android\tools\bin
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\erdem\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM C7000 (mobile) • 20f9d407         • android-arm64  • Android 8.0.0 (API 26)
    • EML L09 (mobile)  • BPN7N18419008822 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!
```
</details>

<details>
<summary>Exception Message</summary>

```
PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] c.e.a.g.c.b(byte[])' on a null object reference
	at c.e.a.f.k(Unknown Source:11)
	at c.e.a.f.r(Unknown Source:7)
	at c.e.a.f.e(Unknown Source:0)
	at c.e.a.e.run(Unknown Source:153)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null)
```
</details>

**Comment by eliasjtg** [comment]
I use this plugin in older version with android embed v1, i'm developing a new app with v2 and it trow 'No implementation found for method write' exception, i need store credentials

**Comment by mvacha** [comment]
We are also experiencing this issue - we have over 16K users with Xiaomi Redmi Note 8 Pro and 23K crashes in the last 14 days caused by this issue. The only workaround we have found is to tell users to reinstall the app.

**Comment by juliansteenbakker** [comment]
Right now the problem is i can't test it because i don't have a device that is affected. Because of this i don't know what the cause is, and if version 5.0.0-beta will fix it. I hope you guys can either figure out whats causing this, or are able to check wether version 5.0.0 still prompts this issue.

**Comment by mvacha** [comment]
We will try to debug the issue later today (right now we are waiting for courier with the Redmi Note 8 Pro) and let you know. Also correct me if I’m wrong, but my understanding is that the fix in 5.0 is either allowing resetOnError or using EncryptedSharedPreferences. So if the user has already hit this issue, he will loose his data.
________________________________

**Comment by juliansteenbakker** [comment]
Yes indeed. The problem seems to be something with the Xiaomi or Huawei devices losing their private keys for the encrypted prefs and thus, aren't able to access it anymore. There are also reports from other devices but it's mainly Huawei and Xiaomi.

**Comment by mvacha** [comment]
Thank you. For our app 90 % of devices hitting this issue are made by Xiaomi and 86 % are Redmi Note 8 Pro, every other model is < 1 %.
________________________________

**Comment by mvacha** [comment]
I can confirm this issue happens after updating from Android 10 to Android 11 (more specifically MIUI 12.5.3 with Android 11). This is the full exception:
```
[   +7 ms] I/flutter (19308): ----------------FIREBASE CRASHLYTICS----------------
[        ] I/flutter (19308): PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.it_nomads.fluttersecurestorage.ciphers.StorageCipher.encrypt(byte[])' on a null object reference
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.write(FlutterSecureStoragePlugin.java:133)
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$200(FlutterSecureStoragePlugin.java:30)
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:189)
[        ] I/flutter (19308): 	at android.os.Handler.handleCallback(Handler.java:938)
[        ] I/flutter (19308): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] I/flutter (19308): 	at android.os.Looper.loop(Looper.java:236)
[        ] I/flutter (19308): 	at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] I/flutter (19308): , null)
[        ] I/flutter (19308): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
[        ] I/flutter (19308): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
[        ] I/flutter (19308): <asynchronous suspension>
[        ] I/flutter (19308): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[        ] I/flutter (19308): #3      FlutterSecureStorage.write (package:flutter_secure_storage/flutter_secure_storage.dart:28:22)
[        ] I/flutter (19308): #4      AuthManager.setServiceLocked (package:<<appName>>/api/authManager.dart:34:19)
[        ] I/flutter (19308): #5      <<appName>>AppState.initState (package:<<appName>>/application.dart:87:18)
[        ] I/flutter (19308): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
[        ] I/flutter (19308): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
[        ] I/flutter (19308): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
[        ] I/flutter (19308): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
[        ] I/flutter (19308): #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
[        ] I/flutter (19308): #11     Ren
[        ] I/flutter (19308): ----------------------------------------------------
[ +119 ms] D/FlutterSecureStoragePl(19308): Initializing StorageCipher
[   +6 ms] E/FlutterSecureStoragePl(19308): StorageCipher initialization failed
[        ] E/FlutterSecureStoragePl(19308): java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:263)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:303)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePrivateKeyFromKeystore(AndroidKeyStoreProvider.java:324)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:388)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:105)
[        ] E/FlutterSecureStoragePl(19308): 	at java.security.KeyStore.getKey(KeyStore.java:1062)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:118)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:38)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:72)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(FlutterSecureStoragePlugin.java:30)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:182)
[        ] E/FlutterSecureStoragePl(19308): 	at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/FlutterSecureStoragePl(19308): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/FlutterSecureStoragePl(19308): 	at android.os.Looper.loop(Looper.java:236)
[        ] E/FlutterSecureStoragePl(19308): 	at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] E/FlutterSecureStoragePl(19308): Caused by: android.security.KeyStoreException: Invalid key blob
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:265)
[        ] E/FlutterSecureStoragePl(19308): 	... 15 more
[  +24 ms] I/flutter (19308): ----------------FIREBASE CRASHLYTICS----------------
[        ] I/flutter (19308): The following exception was thrown unhandled api exception:
[        ] I/flutter (19308): PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.it_nomads.fluttersecurestorage.ciphers.StorageCipher.decrypt(byte[])' on a null object reference
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:162)
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:143)
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$300(FlutterSecureStoragePlugin.java:30)
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:196)
[        ] I/flutter (19308): 	at android.os.Handler.handleCallback(Handler.java:938)
[        ] I/flutter (19308): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] I/flutter (19308): 	at android.os.Looper.loop(Looper.java:236)
[        ] I/flutter (19308): 	at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] I/flutter (19308): , null)
[        ] I/flutter (19308): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
[        ] I/flutter (19308): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
[        ] I/flutter (19308): <asynchronous suspension>
[        ] I/flutter (19308): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[        ] I/flutter (19308): #3      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:45:41)
[        ] I/flutter (19308): #4      AuthManager.actualProfileName (package:<<appName>>/api/authManager.dart:42:46)
[        ] I/flutter (19308): #5      AuthManager.getActualSession (package:<<appName>>/api/authManager.dart:104:54)
[        ] I/flutter (19308): #6      ApiClient._getAuthSession (package:<<appName>>/api/apiClient.dart:275:50)
[        ] I/flutter (19308): #7      ApiClient.postRequest (package:<<appName>>/api/apiClient.dart:1318:48)
[        ] I/flutter (19308): #8      ApiClient.registerNotification.<anonymous closure> (package:<<appName>>/api/apiClient.dart:1133:35)
[        ] I/flutter (19308): #9      ApiClient._handleConnectivityAndAuthErrors.result (package:<<appName>>/api/apiClient.dart:1516:28)
[        ] I/flutter (19308): <asynchronous suspension>
[        ] I/flutter (19308): #10     ApiClient._handleConnectivityAndAuthEr
[        ] I/flutter (19308): ----------------------------------------------------
[        ] I/flutter (19308): PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.it_nomads.fluttersecurestorage.ciphers.StorageCipher.decrypt(byte[])' on a null object reference
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:162)
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:143)
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$300(FlutterSecureStoragePlugin.java:30)
[        ] I/flutter (19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:196)
[        ] I/flutter (19308): 	at android.os.Handler.handleCallback(Handler.java:938)
[        ] I/flutter (19308): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] I/flutter (19308): 	at android.os.Looper.loop(Looper.java:236)
[        ] I/flutter (19308): 	at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] I/flutter (19308): , null)
[ +403 ms] D/FlutterSecureStoragePl(19308): Initializing StorageCipher
[   +5 ms] E/FlutterSecureStoragePl(19308): StorageCipher initialization failed
[        ] E/FlutterSecureStoragePl(19308): java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:263)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:303)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePrivateKeyFromKeystore(AndroidKeyStoreProvider.java:324)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:388)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:105)
[        ] E/FlutterSecureStoragePl(19308): 	at java.security.KeyStore.getKey(KeyStore.java:1062)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:118)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:38)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:72)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(FlutterSecureStoragePlugin.java:30)
[        ] E/FlutterSecureStoragePl(19308): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:182)
[        ] E/FlutterSecureStoragePl(19308): 	at android.os.Handler.handleCallback(Handler.java:938)
[        ] E/FlutterSecureStoragePl(19308): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/FlutterSecureStoragePl(19308): 	at android.os.Looper.loop(Looper.java:236)
[        ] E/FlutterSecureStoragePl(19308): 	at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] E/FlutterSecureStoragePl(19308): Caused by: android.security.KeyStoreException: Invalid key blob
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
[        ] E/FlutterSecureStoragePl(19308): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:265)
[        ] E/FlutterSecureStoragePl(19308): 	... 15 more
```

**Comment by mvacha** [comment]
Ok, so I was able to test that calling `deleteAll()` does not fix problem, therefore neither does #279. What might help is catching the exception here https://github.com/mogol/flutter_secure_storage/blob/develop/flutter_secure_storage/android/src/main/java/com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation.java#L111 and recreating the keys. I'll try it later.

There is an issue in the flutter repo that sums things up nicely https://github.com/flutter/flutter/issues/15307 - TLDR: avoid SharedSecuredStorage if you need something that works reliably. I've also discussed this issue with a friend who leads the development of a much larger app (30M+ users) and he said the same thing. Probably a good take away from this is that new apps should opt-in to use EncryptedSharedPreferences, and that #278 would be really helpful.

**Comment by juliansteenbakker** [comment]
I have released v5.0.0 with lots of improvements for this issue. Please try again or comment if the issue still exists.

**Comment by AristideVB** [comment]
Still having this issue on a Redmi device

**Comment by HHJari** [comment]
This issue still seem to happen with version 9.0.0 to some Androids our users are using:

```
PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.it_nomads.fluttersecurestorage.ciphers.StorageCipher.encrypt(byte[])' on a null object reference
	at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.write(SourceFile:28)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(SourceFile:283)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
, null)
```

Devices:
```
Google  Pixel 2
Realme  RMX3263
Realme  RMX3231
Vivo 1906
Samsung SM-G930W8
Samsung  SM-N950F
Samsung  SM-G960W
OPPO  CPH1853
OPPO  CPH1909
OPPO F1s
OPPO  CPH1933
Lenovo TB-8505X
Xiaomi  Redmi 7
```

Unfortunately I do not have Android OS version listings for those.

**Comment by frankvollebregt** [comment]
I am experiencing the same issue mentioned by @HHJari above, on a Honeywell ScanPal EDA71 tablet running Android 8.1. Deleting all app-data resolves the issue, but isn't desirable of course. I'm using version 9.2.2 of the package.

@HHJari how did it go with `backups` disabled? Have you found a fix or workaround to resolve the issue?

**Comment by brandon-watkins-avcrm** [comment]
Any progress/updates on this?
