### ISSUE TITLE
StorageCipher initialization failed

### ISSUE THREAD

**Issue by jaripekkala** [mogol/flutter_secure_storage#201]
Hi,

and thanks for the package.

Our ITs stumbled into this quite rare case, where the StorageCipher initialization fails when

1. User closes the app, at the same time when the initialization is ongoing
2. Opens the app again

Logcat:

```log
02-04 06:19:30.374  2984  3028 I flutter : Observatory listening on http://127.0.0.1:34095/Z8_vUpisYrM=/
02-04 06:19:30.914  2984  2984 D SurfaceView: surfaceChanged (720,1516) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{813fd4c V.E...... ......ID 0,0-720,1516}
02-04 06:19:34.486  2984  3046 D FlutterSecureStoragePl: Initializing StorageCipher
02-04 06:19:34.492  2984  3046 I fluttersecurestorage: Creating keys!
02-04 06:19:34.511  2984  3046 I fluttersecurestorage: Initializing
02-04 06:19:34.515  2984  3046 I fluttersecurestorage: Generating key pair
02-04 06:19:34.515  4487  4487 I keystore: del (USRPKEY_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.517  4487  4487 I keystore: del (USRSKEY_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.518  4487  4487 I keystore: del (USRCERT_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.520  4487  4487 I keystore: del (CACERT_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.521  4487  4487 I keystore: del (USRCSR_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.524  4487  4487 I keystore: del (USRPKEY_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.526  4487  4487 I keystore: del (USRSKEY_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.527  4487  4487 I keystore: del (USRCERT_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.528  4487  4487 I keystore: del (CACERT_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.529  4487  4487 I keystore: del (USRCSR_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.532  4487  4487 I keystore: del (USRPKEY_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.533  4487  4487 I keystore: del (USRSKEY_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.534  4487  4487 I keystore: del (USRCERT_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.536  4487  4487 I keystore: del (CACERT_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)
02-04 06:19:34.537  4487  4487 I keystore: del (USRCSR_com.org.app.FlutterSecureStoragePluginKey), (10209), (0)

02-04 06:19:43.325  4684  4684 D SurfaceView: onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{ea10b52 V.E...... ......I. 0,0-0,0} of ViewRootImpl@ce2ebb4[MainActivity]
02-04 06:19:43.386  4684  4684 D SurfaceView: surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{ea10b52 V.E...... ......ID 0,0-720,1516}
02-04 06:19:43.453  4684  4771 I flutter : Observatory listening on http://127.0.0.1:42075/4g7YKLy44-Q=/
02-04 06:19:44.410  4684  4684 D SurfaceView: surfaceChanged (720,1516) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{ea10b52 V.E...... ......ID 0,0-720,1516}
02-04 06:19:49.968  4684  4809 D FlutterSecureStoragePl: Initializing StorageCipher
02-04 06:19:50.080  4684  4809 W KeyStore: get() : not found key : USRCERT_com.org.app.FlutterSecureStoragePluginKey
02-04 06:19:50.092  4684  4809 W KeyStore: get() : not found key : CACERT_com.org.app.FlutterSecureStoragePluginKey
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: StorageCipher initialization failed
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: java.lang.Exception: No certificate found under alias: com.org.app.FlutterSecureStoragePluginKey
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.getPublicKey(RSACipher18Implementation.java:95)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.wrap(RSACipher18Implementation.java:42)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:56)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:72)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(FlutterSecureStoragePlugin.java:30)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:182)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at android.os.Handler.handleCallback(Handler.java:883)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at android.os.Looper.loop(Looper.java:237)
02-04 06:19:50.094  4684  4809 E FlutterSecureStoragePl: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

I've managed to reproduce this only couple of times, so I hope this very rare case make any sense in the code level and could be fixed :pray:

**Comment by mogol** [comment]
Hey @jaripekkala 
Looks like the library has to be more careful when handling initialization. Thanks for the report. Will take a look.

**Comment by smasinde** [comment]
Getting the same..

**Comment by rmControls** [comment]
If you clear app data manually....

you will see this error...

any fix for it??

**Comment by fzyzcjy** [comment]
Same issue here

```
2021-07-18 14:45:13.148 25698-25731/? E/FlutterSecureStoragePl: StorageCipher initialization failed
    java.lang.Exception: No certificate found under alias: com.cjy.yplusplus.FlutterSecureStoragePluginKey
        at e.f.a.b.a.b(SourceFile:6)
        at e.f.a.b.a.a(SourceFile:1)
        at e.f.a.b.b.<init>(SourceFile:13)
        at e.f.a.a.b(SourceFile:5)
        at e.f.a.a.a(SourceFile:1)
        at e.f.a.a$b.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by fzyzcjy** [comment]
Is there any ways to solve this? Thanks!

**Comment by fzyzcjy** [comment]
@mogol Hi, is there any way to solve this? Thank you!

**Comment by juliansteenbakker** [comment]
I think this is the same issue as #175 so i am closing this as duplicate.
