### ISSUE TITLE
Attempt to invoke virtual method 'void d.a.b.a.j.a(d.a.b.a.j$c)' on a null object reference

### ISSUE THREAD

**Issue by pavanvora** [mogol/flutter_secure_storage#207]
**Logs from Firebase Crashlytics**
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void d.a.b.a.j.a(d.a.b.a.j$c)' on a null object reference
       at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivityForConfigChanges(FlutterEnginePluginRegistry.java)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java)
       at io.flutter.embedding.engine.FlutterEngine.access$000(FlutterEngine.java)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java)
       at android.app.Activity.performDestroy(Activity.java:6422)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3822)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3853)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Issue occurs only for certain android devices.

Package version - 3.3.3
Flutter version - 1.20.1
Android version - 6.0.1

**Comment by juliansteenbakker** [comment]
The log is minified so we cant exactly see what is wrong here. Please provide deminified log and I'll reopen this.

**Comment by acoutts** [comment]
Can we please re-open this issue? I have a user with the same problem.

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: {exception: PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] e.k.a.e.c.a(byte[])' on a null object reference
	at e.k.a.d.x(FlutterSecureStoragePlugin.java:3)
	at e.k.a.d.d(FlutterSecureStoragePlugin.java:1)
	at e.k.a.d$b.run(FlutterSecureStoragePlugin.java:32)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null), context: {}}. Error thrown Error changing password.
       at ChangeConfirmPasswordScreenState.parsePassword(change_confirm_password.dart:148)
       at ChangeConfirmPasswordScreenState.onChanged(change_confirm_password.dart:121)
```

**Comment by jjvillavicencio** [comment]
I have the same error in certain devices, I register the error with crashlytics

**Package version**
flutter_secure_storage: 6.0.0

**Error**
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] x7.i.a(byte[])' on a null object reference
	at w7.a.m(Unknown Source:24)
	at w7.e$b.run(Unknown Source:267)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null). Error thrown [local_provider] (saveRoles).
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:119)
       at LocalProvider.saveRoles.<fn>(local_provider.dart:107)
```

**Device**

Dispositivo
Marca:Xiaomi
Modelo:MI 8 Lite
Orientación: Vertical
Memoria RAM disponible: 2.62 GB
Espacio disponible en el disco: 84.39 GB
Sistema operativo
Versión:Android 10
Orientación: Vertical
Con derechos de administrador:No
