### ISSUE TITLE
Null check operator used on a null value on read method

### ISSUE THREAD

**Issue by migcarde** [mogol/flutter_secure_storage#208]
Hi, when I try to use secure_storage with version 4.0.0 i have that issue:

![image](https://user-images.githubusercontent.com/29870701/108634641-c54e3080-747a-11eb-9aad-956ddecf1ece.png)

My error:

```
E/flutter ( 7886): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7886): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter ( 7886): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter ( 7886): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter ( 7886): #3      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:44:42)
E/flutter ( 7886): #4      SecureStorage.getToken (package:youm/helpers/secure_storage.dart:11:36)
E/flutter ( 7886): #5      checkLogin (package:youm/main.dart:15:39)
E/flutter ( 7886): #6      main (package:youm/main.dart:11:37)
E/flutter ( 7886): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:146:25)
E/flutter ( 7886): #8      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 7886): #9      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 7886): #10     _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 7886): #11     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 7886): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:139:5)
E/flutter ( 7886): #13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 7886): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 7886):
```

My flutter doctor:

```
[√] Flutter (Channel dev, 1.27.0-4.0.pre, on Microsoft Windows [VersiÃ³n 10.0.19042.804], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (2 available)
! Doctor found issues in 1 category.
```
Flutter version:  1.27.0-4.0.pre • channel dev

**Comment by mogol** [comment]
Hey @migcarde 
Looks like you are accessing plugins (in this case, flutter secure storage) before you call `runApp` in main function. 
You have to either move the call in some widget or call [WidgetsFlutterBinding.ensureInitialized()](https://api.flutter.dev/flutter/widgets/WidgetsFlutterBinding/ensureInitialized.html) before `runApp`.

**Comment by migcarde** [comment]
So many thanks @mogol!! Sorry for the inefficient issue, I proceed to close it
