### ISSUE TITLE
Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder'

### ISSUE THREAD

**Issue by NebulaFox** [mogol/flutter_secure_storage#209]
Get the below error in emulator on API 19. Unable to test on API 21 and 22 as I was unable to get an app to install on fresh emulators. Have found it works on emulators API 23+.

Package version - 3.3.5

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Mac OS X 10.14.6 18G8022
    darwin-x64, locale en-GB)
    • Flutter version 1.26.0-17.6.pre at /usr/local/flutter
    • Framework revision a29104a69b (7 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/robbiebykowski/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/robbiebykowski/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
```

</details>

```
D/FlutterSecureStoragePl( 2787): Initializing StorageCipher
E/dalvikvm( 2787): Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createKeys
W/dalvikvm( 2787): VFY: unable to resolve new-instance 283 (Landroid/security/keystore/KeyGenParameterSpec$Builder;) in Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;
D/dalvikvm( 2787): VFY: replacing opcode 0x22 at 0x0080
W/dalvikvm( 2787): VFY: unable to resolve exception class 285 (Landroid/security/keystore/StrongBoxUnavailableException;)
W/dalvikvm( 2787): VFY: unable to find exception handler at addr 0xf5
W/dalvikvm( 2787): VFY:  rejected Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;.createKeys (Landroid/content/Context;)V
W/dalvikvm( 2787): VFY:  rejecting opcode 0x0d at 0x00f5
W/dalvikvm( 2787): VFY:  rejected Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;.createKeys (Landroid/content/Context;)V
W/dalvikvm( 2787): Verifier rejected class Lcom/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation;
W/dalvikvm( 2787): threadid=14: thread exiting with uncaught exception (group=0x9cd0bb20)
E/AndroidRuntime( 2787): FATAL EXCEPTION: com.it_nomads.fluttersecurestorage.worker
E/AndroidRuntime( 2787): Process: com.example.petid, PID: 2787
E/AndroidRuntime( 2787): java.lang.VerifyError: com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation
E/AndroidRuntime( 2787): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
E/AndroidRuntime( 2787): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:72)
```

**Comment by matpag** [comment]
There is a bug in the library currently, I will check if I can send a PR for this

**Comment by juliansteenbakker** [comment]
A fix has been merged so it should not give any crash anymore. If it does, please feel free to comment and I'll reopen this.
