### ISSUE TITLE
compatibility with the web

### ISSUE THREAD

**Issue by simo9900** [mogol/flutter_secure_storage#215]
Hi

Is this package compatible with the flutter web? How can I use it?

I have this error:

```
Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:56933/dart_sdk.js:5334:11)
    at Function._operatingSystem (http://localhost:56933/dart_sdk.js:56144:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:56933/dart_sdk.js:56190:27)
    at get _operatingSystem (http://localhost:56933/dart_sdk.js:56103:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:56933/dart_sdk.js:5839:17)
    at get isLinux (http://localhost:56933/dart_sdk.js:56115:26)
    at Function.desc.get [as isLinux] (http://localhost:56933/dart_sdk.js:5839:17)
    at flutter_secure_storage.FlutterSecureStorage.new.[_selectOptions] (http://localhost:56933/packages/flutter_secure_storage/flutter_secure_storage.dart.lib.js:175:33)
    at flutter_secure_storage.FlutterSecureStorage.new.read (http://localhost:56933/packages/flutter_secure_storage/flutter_secure_storage.dart
```

**Comment by KammererTob** [comment]
There currently is no web support. Please check out https://github.com/mogol/flutter_secure_storage/issues/96 for more info.
