### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Roshan-24** [mogol/flutter_secure_storage#219]
```dart
Future<void> main() async {
  final HttpLink httpLink = HttpLink('http://localhost:4000/graphql');
  final storage = new FlutterSecureStorage();
  final _token = await storage.read(key: 'accessToken');
  final AuthLink authLink = AuthLink(getToken: () => 'Bearer $_token');
  final Link link = authLink.concat(httpLink);
  final ValueNotifier<GraphQLClient> client = ValueNotifier(
    GraphQLClient(link: link, cache: GraphQLCache(store: InMemoryStore()))
  );

  runApp(
    GraphQLProvider(
      client: client,
      child: MyApp(),
    )
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: ListScreen(),
    );
  }  
}
```

I am a dart/flutter beginner and i am trying to setup a graphql client with a jwt token on startup, but when i try to access the secure storage in the main(), i get this error:

```
E/flutter ( 4064): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 4064): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter ( 4064): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter ( 4064): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter ( 4064): #3      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:50:42)
E/flutter ( 4064): #4      main (package:flutter_graphql_client/main.dart:12:26)
E/flutter ( 4064): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:146:25)
E/flutter ( 4064): #6      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 4064): #7      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 4064): #8      _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 4064): #9      runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 4064): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:139:5)
E/flutter ( 4064): #11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 4064): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 4064): 
```

Is it meant to work like this and am i doing something wrong? If yes, then how do i go about doing this

**Comment by Roshan-24** [comment]
I guess i shouldn't call secure storage functions before the rupApp() call, makes sense. I instead initialized secure storage and graphql client in MyApp stateful widget and it works fine. Closing this issue

**Comment by KDCinfo** [comment]
I use `WidgetsFlutterBinding.ensureInitialized()` to set up initialization before the `runApp()`:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await setupServiceLocator();
  runApp(MyApp());
}
```
