### ISSUE TITLE
IllegalStateException on a device with no pin/security

### ISSUE THREAD

**Issue by duzenko** [mogol/flutter_secure_storage#303]
Do we need a pin lock for out app to start? Here's the log file from LG G4
```
E/FlutterSecureStoragePl( 3460): StorageCipher initialization failed
E/FlutterSecureStoragePl( 3460): java.lang.IllegalStateException: could not generate key in keystore
E/FlutterSecureStoragePl( 3460): 	at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:99)
E/FlutterSecureStoragePl( 3460): 	at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
E/FlutterSecureStoragePl( 3460): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createKeys(RSACipher18Implementation.java:195)
E/FlutterSecureStoragePl( 3460): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:121)
E/FlutterSecureStoragePl( 3460): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:39)
E/FlutterSecureStoragePl( 3460): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
E/FlutterSecureStoragePl( 3460): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitStorageCipher(FlutterSecureStoragePlugin.java:73)
E/FlutterSecureStoragePl( 3460): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$000(FlutterSecureStoragePlugin.java:30)
E/FlutterSecureStoragePl( 3460): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:184)
E/FlutterSecureStoragePl( 3460): 	at android.os.Handler.handleCallback(Handler.java:739)
E/FlutterSecureStoragePl( 3460): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/FlutterSecureStoragePl( 3460): 	at android.os.Looper.loop(Looper.java:135)
E/FlutterSecureStoragePl( 3460): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```
Relevant SO question: https://stackoverflow.com/questions/30736787/cannot-generate-key-in-android-keystore

**Comment by duzenko** [comment]
Regret adding a pin lock did not help

**Comment by duzenko** [comment]
Seemingly v 5.0 beta works with android options
