### ISSUE TITLE
StorageCipher initialization failed

### ISSUE THREAD

**Issue by kaseyrossanderson** [mogol/flutter_secure_storage#304]
This seems to be the same error reported in [159](https://github.com/mogol/flutter_secure_storage/issues/159) that is currently closed. However, using both 4.2.1 as well as trying the 5.0.0-beta.5 beta version is resulting in the same error.

Note, that this seems to work on my iPhone and it's failing on the Pixel 5 emulator.

```
E/FlutterSecureStoragePl( 6441): StorageCipher initialization failed
E/FlutterSecureStoragePl( 6441): java.security.UnrecoverableKeyException: Failed to obtain information about private key
E/FlutterSecureStoragePl( 6441): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:223)
E/FlutterSecureStoragePl( 6441): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
E/FlutterSecureStoragePl( 6441): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePrivateKeyFromKeystore(AndroidKeyStoreProvider.java:269)
E/FlutterSecureStoragePl( 6441): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:94)
E/FlutterSecureStoragePl( 6441): 	at java.security.KeyStore.getKey(KeyStore.java:1062)
E/FlutterSecureStoragePl( 6441): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:115)
E/FlutterSecureStoragePl( 6441): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:35)
E/FlutterSecureStoragePl( 6441): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:29)
E/FlutterSecureStoragePl( 6441): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitialized(FlutterSecureStoragePlugin.java:95)
E/FlutterSecureStoragePl( 6441): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$100(FlutterSecureStoragePlugin.java:37)
E/FlutterSecureStoragePl( 6441): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:256)
E/FlutterSecureStoragePl( 6441): 	at android.os.Handler.handleCallback(Handler.java:790)
E/FlutterSecureStoragePl( 6441): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/FlutterSecureStoragePl( 6441): 	at android.os.Looper.loop(Looper.java:164)
E/FlutterSecureStoragePl( 6441): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/FlutterSecureStoragePl( 6441): Caused by: android.security.KeyStoreException: Invalid key blob
E/FlutterSecureStoragePl( 6441): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
E/FlutterSecureStoragePl( 6441): 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:224)
E/FlutterSecureStoragePl( 6441): 	... 14 more
E/flutter ( 6441): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.it_nomads.fluttersecurestorage.ciphers.StorageCipher.decrypt(byte[])' on a null object reference
E/flutter ( 6441): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:216)
E/flutter ( 6441): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:198)
E/flutter ( 6441): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$500(FlutterSecureStoragePlugin.java:37)
E/flutter ( 6441): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:257)
E/flutter ( 6441): 	at android.os.Handler.handleCallback(Handler.java:790)
E/flutter ( 6441): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 6441): 	at android.os.Looper.loop(Looper.java:164)
E/flutter ( 6441): 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

I'm fairly certain that I tested this same device on emulator yesterday and it worked.. but I may be mistaken.

**Comment by kaseyrossanderson** [comment]
I decided to delete the existing android emulator device I was using (Pixel 5) and re-creating and it works again with the same device. I think I know what I did to cause this error to happen..

In Android Studio I used the 'Wipe Device' feature after the app had already stored some keys in the keystore/keychain. Then when relaunching the app I got the error previously mentioned. I'm guessing that the keychain/keystore was wiped but the app still thought it had a secret key to access the secure data with? or vise versa? Not sure if this is an issue or not so wanted to provide this input.

**Comment by juliansteenbakker** [comment]
Normally this means that the key can't be accessed anymore. There are several other issues about this. I would suggest you look in this thread about the problem and try the possible workaround: https://github.com/mogol/flutter_secure_storage/issues/175#issuecomment-890958005.
