### ISSUE TITLE
KeyStore exception

### ISSUE THREAD

**Issue by vela1606** [mogol/flutter_secure_storage#32]
Console Output:

`
W/KeyStore( 8212): KeyStore exception
W/KeyStore( 8212): android.os.ServiceSpecificException:  (code 7)
W/KeyStore( 8212): 	at android.os.Parcel.createException(Parcel.java:1956)
W/KeyStore( 8212): 	at android.os.Parcel.readException(Parcel.java:1910)
W/KeyStore( 8212): 	at android.os.Parcel.readException(Parcel.java:1860)
W/KeyStore( 8212): 	at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
W/KeyStore( 8212): 	at android.security.KeyStore.get(KeyStore.java:195)
W/KeyStore( 8212): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
W/KeyStore( 8212): 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
W/KeyStore( 8212): 	at java.security.KeyStore.getEntry(KeyStore.java:1560)
W/KeyStore( 8212): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.getEntry(RSACipher18Implementation.java:69)
W/KeyStore( 8212): 	at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.wrap(RSACipher18Implementation.java:34)
W/KeyStore( 8212): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:56)
W/KeyStore( 8212): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.<init>(FlutterSecureStoragePlugin.java:46)
W/KeyStore( 8212): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(FlutterSecureStoragePlugin.java:33)
W/KeyStore( 8212): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:22)
W/KeyStore( 8212): 	at com.mdtimeline.app.mdtimelineapp.MainActivity.onCreate(MainActivity.kt:11)
W/KeyStore( 8212): 	at android.app.Activity.performCreate(Activity.java:7136)
W/KeyStore( 8212): 	at android.app.Activity.performCreate(Activity.java:7127)
W/KeyStore( 8212): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
W/KeyStore( 8212): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
W/KeyStore( 8212): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
W/KeyStore( 8212): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/KeyStore( 8212): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/KeyStore( 8212): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/KeyStore( 8212): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
W/KeyStore( 8212): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/KeyStore( 8212): 	at android.os.Looper.loop(Looper.java:193)
W/KeyStore( 8212): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/KeyStore( 8212): 	at java.lang.reflect.Method.invoke(Native Method)
W/KeyStore( 8212): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/KeyStore( 8212): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`
pubspec.yaml:
`
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #cupertino_icons: ^0.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_date_picker: "^0.1.8"
  intl: 0.15.7
  barcode_scan: "^0.0.4"
  http: ^0.12.0
  url_launcher: 4.0.1
  async_loader: ^0.1.2
  flutter_secure_storage: ^3.1.2
  local_auth: ^0.3.0
  device_info: ^0.3.0
  shared_preferences: ^0.4.3
  uni_links: ^0.1.4
  json_serializable: ^2.0.0
  progress_hud: ^1.1.0
  event_bus: ^1.0.1
  flutter_cupertino_date_picker: ^0.2.0
`

Flutter doctor:
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.13, on Mac OS X 10.14.1 18B75, locale en-PR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
[✓] Connected device (1 available)

• No issues found!
`

**Comment by bm-software** [comment]
@vela1606 This issue still exists both on API 27 and 28. How can I solve this?

**Comment by sjmcdowall** [comment]
We are as well and I am on 28 too.

**Comment by joeythomaschaske** [comment]
Tested on api level 29 and am getting this error as well
