### ISSUE TITLE
Unable to .readAll() keys on Android 9 (API 28)

### ISSUE THREAD

**Issue by hensou** [mogol/flutter_secure_storage#337]
### Issue
The library fails whenever I try to read all keys. 
But when I try to read the keys individually, it works flawlessly.

### Platform where the issue was observed
**Device:** Xiaomi Mi A1
**OS:** Android 9 (API 28)

### Exception Thrown:
```
io.flutter.plugins.firebase.crashlytics.FlutterError: 
PlatformException(Exception encountered, readAll, 
java.lang.SecurityException: Could not decrypt key. decryption failed
	at a.g.a.a.c(Unknown Source:58)
	at a.g.a.a.getAll(Unknown Source:49)
	at b.b.a.d.x(Unknown Source:2)
	at b.b.a.d.i(Unknown Source:0)
	at b.b.a.d$b.run(Unknown Source:200)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.security.GeneralSecurityException: decryption failed
	at b.a.c.a.u.c$a.b(Unknown Source:116)
	at a.g.a.a.c(Unknown Source:13)
	... 8 more
, null). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(StandardMethodCodec.java:607)
       at MethodChannel._invokeMethod(MethodChannel.java:167)
       at MethodChannelFlutterSecureStorage.readAll(MethodChannelFlutterSecureStorage.java:61)
       at SupabaseAuthRepository._init(SupabaseAuthRepository.java:69)
```

### Flutter Doctor
```
[✓] Flutter (Channel beta, 2.8.0-3.2.pre, on Microsoft Windows [Version 10.0.22504.1000], locale en-GB)
    • Flutter version 2.8.0-3.2.pre at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2901cd7208 (21 hours ago), 2021-11-18 11:15:09 -0800
    • Engine revision bcc2b7f12c
    • Dart version 2.15.0 (build 2.15.0-268.18.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\***\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\***\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\***\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\***\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7784292\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Google\Chrome Dev\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\***\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7784292
    • Flutter plugin version 62.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at C:\Users\***\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Mi A1 (mobile) • g46zd4181904 • android-arm64  • Android 9 (API 28)

• No issues found!
```

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
