### ISSUE TITLE
DeleteAll crashing for some users

### ISSUE THREAD

**Issue by BenevidesLecontes** [mogol/flutter_secure_storage#347]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference
       at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.deleteAll(FlutterSecureStoragePlugin.java:193)
       at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$800(FlutterSecureStoragePlugin.java:37)
       at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:350)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by tahitiangabriel** [comment]
I'm also having the same error with V5.0.2.

`PlatformException(Exception encountered, delete, java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.n(SourceFile:1)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.h(SourceFile:1)
	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$b.run(SourceFile:10)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null)
`

**Comment by ragnor-rs** [comment]
the same
Redmi Note 5, Android 9

**Comment by acoutts** [comment]
Saw the same error on a Pixel 6.

**Comment by acoutts** [comment]
Actually i'm having the same issue but when i call the `write()` method. The root cause seems to be that `preferences` is null / uninitialized.

The `write` method first calls `ensureInitialized`. In this method, the actual value for `preferences` gets populated either as a `SharedPreferences` instance from `nonEncryptedPreferences` or the return value from `initializeEncryptedSharedPreferencesManager()`.


The encrypted shared preferences manager function can throw an error if something goes wrong. In this case, the error is silently logged and the `ensureInitialized` function returns normally without the value of `sharedPrefrences` actually ever being set.

<img width="1111" alt="Screen Shot 2022-08-19 at 10 33 54 AM" src="https://user-images.githubusercontent.com/9597207/185642288-428669e8-7856-47fe-ba78-81c1ab5978ca.png">

The write function then attempts to use the shared preferences instance:
<img width="765" alt="Screen Shot 2022-08-19 at 10 34 58 AM" src="https://user-images.githubusercontent.com/9597207/185642492-03d349de-e902-40aa-8c15-6ae9f37b8f36.png">

But at this point `preferences` is uninitialized (null) and the write call returns a platform error to dart:
```
PlatformException: PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference
	at e.p.a.d.x(FlutterSecureStoragePlugin.java:1)
	at e.p.a.d.d(FlutterSecureStoragePlugin.java:1)
	at e.p.a.d$b.run(FlutterSecureStoragePlugin.java:32)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null)
```

There are actually more cases that initialization can fail and the initialize function never throws the error up so there is more unexpected behavior possible.

**Comment by juliansteenbakker** [comment]
]
