### ISSUE TITLE
MissingPluginImplementation weird behavior

### ISSUE THREAD

**Issue by alexviquez** [mogol/flutter_secure_storage#368]
Hi everyone i have a weird behavior with this plugin, im not 100% sure if the plugin is the problem but is related whit the implementation.

Related https://github.com/mogol/flutter_secure_storage/issues/71

Flutter doctor -v

[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.3 20E232 darwin-x64, locale es-MX)
    • Flutter version 1.22.6 at /Users/alejandroviquez/Desktop/development/flutter
    • Framework revision 9b2d32b605 (1 year, 1 month ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

The issue consist in the next, create a new app and install the next plugins:

flutter_secure_storage: ^3.3.4
flutter_facebook_auth: ^2.0.2

in the increment app example, change this code:
```dart
void _incrementCounter() {
    WidgetsFlutterBinding.ensureInitialized();
    setState(() {
      final storage = FlutterSecureStorage();
      storage.read(key: 'some'); // example key
      _counter++;
    });
  }
```

when click the button, the exception appears
```dart
E/flutter (13111): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
E/flutter (13111): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (13111): <asynchronous suspension>
E/flutter (13111): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (13111): #2      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:45:41)
E/flutter (13111): #3      _MyHomePageState._incrementCounter.<anonymous closure> (package:ex2/main.dart:51:15)
```

But the weird is when remove this library -> flutter_facebook_auth: ^2.0.2 everything is corrected, im not sure if this is a problem with the implementation of the other plugin but why broke flutter_secure_storage? 
the problem appears only on android devices
Thanks for read

**Comment by alexviquez** [comment]
Omg i found the solutuion, for some reason if you set directly on manifest configurations without usage of xml, the plugin implementations can be broken, the  solution was the next:
https://github.com/roughike/flutter_facebook_login/issues/262#issuecomment-630542420
