### ISSUE TITLE
W/AndroidKeysetManager( 5792): java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist

### ISSUE THREAD

**Issue by Tom3652** [mogol/flutter_secure_storage#408]
Hello ! 
I have built my app for the first time using this package and I have got this error in the logs. 
Do you know what is the impact / if it's a real bug or i did something wrong ?

```
W/AndroidKeysetManager( 5792): keyset not found, will generate a new one
W/AndroidKeysetManager( 5792): java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
W/AndroidKeysetManager( 5792): 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
W/AndroidKeysetManager( 5792): 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
W/AndroidKeysetManager( 5792): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.initializeEncryptedSharedPreferencesManager(FlutterSecureStoragePlugin.java:136)
W/AndroidKeysetManager( 5792): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitialized(FlutterSecureStoragePlugin.java:105)
W/AndroidKeysetManager( 5792): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$100(FlutterSecureStoragePlugin.java:37)
W/AndroidKeysetManager( 5792): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:337)
W/AndroidKeysetManager( 5792): 	at android.os.Handler.handleCallback(Handler.java:938)
W/AndroidKeysetManager( 5792): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/AndroidKeysetManager( 5792): 	at android.os.Looper.loop(Looper.java:250)
W/AndroidKeysetManager( 5792): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/AndroidKeysetManager( 5792): keyset not found, will generate a new one
W/AndroidKeysetManager( 5792): java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_value_keyset__ does not exist
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
W/AndroidKeysetManager( 5792): 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
W/AndroidKeysetManager( 5792): 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:160)
W/AndroidKeysetManager( 5792): 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
W/AndroidKeysetManager( 5792): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.initializeEncryptedSharedPreferencesManager(FlutterSecureStoragePlugin.java:136)
W/AndroidKeysetManager( 5792): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.ensureInitialized(FlutterSecureStoragePlugin.java:105)
W/AndroidKeysetManager( 5792): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$100(FlutterSecureStoragePlugin.java:37)
W/AndroidKeysetManager( 5792): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:337)
W/AndroidKeysetManager( 5792): 	at android.os.Handler.handleCallback(Handler.java:938)
W/AndroidKeysetManager( 5792): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/AndroidKeysetManager( 5792): 	at android.os.Looper.loop(Looper.java:250)
W/AndroidKeysetManager( 5792): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

Thanks !

**Comment by waqadArshad** [comment]
@Tom3652 @arok @JordyLangen @bbedward @Mosc  can any one of u please provide a solution to this? Thanks.

**Comment by Tom3652** [comment]
I wish i had one but i have no idea what this is about and i could not find relevant answers on StackOverflow / at least be able to test them because it's within the package's code... it doesn't seem to be a configuration error

**Comment by waqadArshad** [comment]
> I wish i had one but i have no idea what this is about and i could not find relevant answers on StackOverflow / at least be able to test them because it's within the package's code... it doesn't seem to be a configuration error

@Tom3652 No worries, I just did flutter clean opened the build.gradle from the "Open in android Studio" option, and restarted the application and it started working. I don't know how it happened but it did. By the way, Thanks for letting me know.

**Comment by juliansteenbakker** [comment]
This means that the sharedPreference database doesn't exist yet and is creating a new one.

**Comment by Tom3652** [comment]
Hi thanks for the reply ! 
So it has no impact on the plugin ? I mean it's working fine anyway after that ? 

Would it be possible to not throw this exception in that case ?

**Comment by juliansteenbakker** [comment]
This exception comes from android itself, not this plugin so i can't do anything about it.

**Comment by Tom3652** [comment]
Oh alright thanks.
