### ISSUE TITLE
the project is not build on Flutter 3.0.5 and Dart 2.17.6

### ISSUE THREAD

**Issue by gevork** [mogol/flutter_secure_storage#421]
When import package:flutter_secure_storage/flutter_secure_storage.dart

I have this error. 

Flutter version 

`Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (3 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
`

> Unhandled exception:
> Crash when compiling null,
> at character offset null:
> Null check operator used on a null value
> #0      DeclaredSourceConstructorBuilder.finalizeSuperInitializingFormals (package:front_end/src/fasta/source/source_constructor_builder.dart:337:48)
> #1      DeclaredSourceConstructorBuilder.inferFormalTypes (package:front_end/src/fasta/source/source_constructor_builder.dart:255:9)
> #2      TypeInferenceEngine.finishTopLevelInitializingFormals (package:front_end/src/fasta/type_inference/type_inference_engine.dart:148:15)
> #3      SourceLoader.checkOverrides (package:front_end/src/fasta/source/source_loader.dart:2176:25)
> #4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:534:14)
> <asynchronous suspension>
> #5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
> <asynchronous suspension>
> #6      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:400:33)
> <asynchronous suspension>
> #7      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:50)
> <asynchronous suspension>
> #8      FrontendCompiler.compile (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:562:11)
> <asynchronous suspension>
> #9      listenAndCompile.<anonymous closure> (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:1199:11)
> <asynchronous suspension>
> 
> #0      DeclaredSourceConstructorBuilder.finalizeSuperInitializingFormals (package:front_end/src/fasta/source/source_constructor_builder.dart:337:48)
> #1      DeclaredSourceConstructorBuilder.inferFormalTypes (package:front_end/src/fasta/source/source_constructor_builder.dart:255:9)
> #2      TypeInferenceEngine.finishTopLevelInitializingFormals (package:front_end/src/fasta/type_inference/type_inference_engine.dart:148:15)
> #3      SourceLoader.checkOverrides (package:front_end/src/fasta/source/source_loader.dart:2176:25)
> #4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:534:14)
> <asynchronous suspension>
> #5      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
> <asynchronous suspension>
> #6      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:400:33)
> <asynchronous suspension>
> #7      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:50)
> <asynchronous suspension>
> #8      FrontendCompiler.compile (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:562:11)
> <asynchronous suspension>
> #9      listenAndCompile.<anonymous closure> (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:1199:11)
> <asynchronous suspension>
> the Dart compiler exited unexpectedly.
> the Dart compiler exited unexpectedly.

**Comment by gevork** [comment]
I solved it by reinstalling Flutter
Remove old dir Flutter and download new!
