### ISSUE TITLE
StandardMethodCodec.decodeEnvelope

### ISSUE THREAD

**Issue by vineetpandit90** [mogol/flutter_secure_storage#428]
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Exception encountered, write, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] com.it_nomads.fluttersecurestorage.e.c.a(byte[])' on a null object reference
	at com.it_nomads.fluttersecurestorage.d.x(FlutterSecureStoragePlugin.java:3)
	at com.it_nomads.fluttersecurestorage.d.d(FlutterSecureStoragePlugin.java:1)
	at com.it_nomads.fluttersecurestorage.d$b.run(FlutterSecureStoragePlugin.java:32)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:607)
       at MethodChannel._invokeMethod(platform_channel.dart:177)

**Comment by acoutts** [comment]
I downgraded to `4.2.1` and this issue is now resolved for me.

**Comment by rmasarovic** [comment]
similar here version 5.2.1: 

 Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.content.SharedPreferences.contains(java.lang.String)' on a null object reference
	at g.f.a.d.b(Unknown Source:5)
	at g.f.a.e$b.run(Unknown Source:221)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.os.HandlerThread.run(HandlerThread.java:67)
, null). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:607)
       at MethodChannel._invokeMethod(platform_channel.dart:167)
       at SecureStorage.getAccessToken(secure_storage_provider.dart:44)

**Comment by felipecastrosales** [comment]
News about it?

**Comment by vineetpandit90** [comment]
Not yet, we will try a new version and let you guys know about this.

**Comment by tologonkudaiberdiuulu** [comment]
@felipecastrosales no, it's not fixed yet. #489 not solved this problem

**Comment by tologonkudaiberdiuulu** [comment]
Any progress on that?

**Comment by MortadhaFadhlaoui** [comment]
+1

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
