### ISSUE TITLE
libsecret_error: Failed to execute child process

### ISSUE THREAD

**Issue by bitinerant** [mogol/flutter_secure_storage#464]
I have been unable to run flutter_secure_storage 6.0.0 on Ubuntu 22.04.

The [example](https://pub.dev/packages/flutter_secure_storage/example) builds successfully (after [uninstalling the Flutter snap](https://github.com/mogol/flutter_secure_storage/issues/362#issuecomment-1163045114) and installing Flutter manually), but when I try to run it it gives the error, `libsecret_error: Failed to execute child process “dbus-launch” (No such file or directory)` in the terminal. The app appears and displays the "Plugin example app" title bar, but clicking the plus icon does nothing in the GUI and displays an additional `libsecret_error` error in the terminal. This happens in both debug and release modes. Other Flutter apps work as expected in this environment.

A full log is below.

```
ubuntu@flutter18:~/flutter_secure_storage_example$ uname -a
Linux flutter18 5.14.0-1046-oem #53-Ubuntu SMP Wed Jul 13 13:15:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@flutter18:~/flutter_secure_storage_example$ sudo apt install -y libsecret-1-dev libjsoncpp-dev libsecret-1-0 libjsoncpp25
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libjsoncpp-dev is already the newest version (1.9.5-3).
libjsoncpp25 is already the newest version (1.9.5-3).
libsecret-1-0 is already the newest version (0.20.5-2).
libsecret-1-dev is already the newest version (0.20.5-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ubuntu@flutter18:~/flutter_secure_storage_example$ flutter clean
Deleting build...                                                   18ms
Deleting .dart_tool...                                               4ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting ephemeral...                                                4ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
ubuntu@flutter18:~/flutter_secure_storage_example$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on Ubuntu 22.04.1 LTS 5.14.0-1046-oem, locale C.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
ubuntu@flutter18:~/flutter_secure_storage_example$ flutter run -d linux
Running "flutter pub get" in flutter_secure_storage_example...        354ms
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

(flutter_secure_storage_example:40241): dbind-WARNING **: 20:55:52.574: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus: No such file or directory

** (flutter_secure_storage_example:40241): WARNING **: 20:55:53.017: libsecret_error: Failed to execute child process “dbus-launch” (No such file or directory)
Syncing files to device Linux...                                    61ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:37029/y4uUNPzeLvw=/
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to execute child process “dbus-launch” (No such file or directory), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      MethodChannelFlutterSecureStorage.readAll (package:flutter_secure_storage_platform_interface/src/method_channel_flutter_secure_storage.dart:61:21)
<asynchronous suspension>
#3      ItemsWidgetState._readAll (package:flutter_secure_storage_example/main.dart:40:17)
<asynchronous suspension>

The Flutter DevTools debugger and profiler on Linux is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:37029/y4uUNPzeLvw=/

** (flutter_secure_storage_example:40241): WARNING **: 20:55:57.676: libsecret_error: Failed to execute child process “dbus-launch” (No such file or directory)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to execute child process “dbus-launch” (No such file or directory), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      ItemsWidgetState._addNewItem (package:flutter_secure_storage_example/main.dart:63:5)
<asynchronous suspension>


** (flutter_secure_storage_example:40241): WARNING **: 20:56:03.004: libsecret_error: Failed to execute child process “dbus-launch” (No such file or directory)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to execute child process “dbus-launch” (No such file or directory), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      ItemsWidgetState._addNewItem (package:flutter_secure_storage_example/main.dart:63:5)
<asynchronous suspension>

Lost connection to device.

(flutter_secure_storage_example:40241): GLib-GObject-WARNING **: 20:56:20.837: ../../../gobject/gsignal.c:2731: instance '0x56184b958030' has no handler with id '222'
ubuntu@flutter18:~/flutter_secure_storage_example$ 

```

**Comment by bitinerant** [comment]
**Update**: this is not a bug in `flutter_secure_storage`. However, it would be helpful if the documentation could be updated.

I was able to get a similar error message without Flutter or `flutter_secure_storage`:

```
$ sudo apt install libsecret-tools
<cut>
$ secret-tool store --label=test3333 attribute test4444  # type: thisissecret
Password: 
secret-tool: Failed to execute child process “dbus-launch” (No such file or directory)
$ 
```

I'm running Flutter in an LXC container which did not have D-Bus or a [libsecret](https://wiki.gnome.org/Projects/Libsecret) 'server'. Les Hazlewood [provided the solution](https://unix.stackexchange.com/a/548005).

Set up once:
```
sudo apt install -y gnome-keyring dbus-x11
mkdir -p ~/.cache ~/.local/share/keyrings
```

For each new terminal, run:
```
eval "$(dbus-launch --sh-syntax)"
eval "$(printf 'NEW_KEYRING_PASSWORD\n' | gnome-keyring-daemon --unlock)"
eval "$(printf 'NEW_KEYRING_PASSWORD\n' | /usr/bin/gnome-keyring-daemon --start)"
```

After this, `secret-tool` and your Flutter app with `flutter_secure_storage` should succeed:
```
secret-tool store --label=test3333 attribute test4444  # type: thisissecret
secret-tool lookup attribute test4444  # should display: thisissecret
```

**Comment by spinus** [comment]
Seems like this issue can be closed as it's not this library issue.

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
