### ISSUE TITLE
error in android

### ISSUE THREAD

**Issue by hussenIbrahim** [mogol/flutter_secure_storage#477]
app stuck in native splash screen 
i called readAll before runApp 

Signal Catcher (runnable):tid=6 systid=24280 
#00 pc 0x53a6e0 libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 128)
#01 pc 0x6f0e04 libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 236)
#02 pc 0x6fe690 libart.so (art::DumpCheckpoint::Run(art::Thread*) + 208)
#03 pc 0x364248 libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*) + 440)
#04 pc 0x6fce30 libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool) + 280)
#05 pc 0x6fc824 libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 292)
#06 pc 0x6d5974 libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 184)
#07 pc 0x6e1994 libart.so (art::SignalCatcher::HandleSigQuit() + 468)
#08 pc 0x574230 libart.so (art::SignalCatcher::Run(void*) + 264)
#09 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#10 pc 0x5288c libc.so (__start_thread + 64)

main (native):tid=1 systid=24275 
#00 pc 0x9fca8 libc.so (__epoll_pwait + 8)
#01 pc 0x1663c libutils.so (android::Looper::pollInner(int) + 180)
#02 pc 0x16520 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 112)
#03 pc 0x152c20 libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int) + 44)
       at android.os.MessageQueue.nativePollOnce(Native method)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

perfetto_hprof_listener (native):tid=7 systid=24281 
#00 pc 0x9ea44 libc.so (read + 4)
#01 pc 0x1d840 libperfetto_hprof.so (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ArtPlugin_Initialize::$_34> >(void*) + 260)
#02 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#03 pc 0x5288c libc.so (__start_thread + 64)

Jit thread pool worker thread 0 (native):tid=8 systid=24282 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x47cc80 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 140)
#02 pc 0x47cb18 libart.so (art::ThreadPool::GetTask(art::Thread*) + 120)
#03 pc 0x6199a4 libart.so (art::ThreadPoolWorker::Run() + 72)
#04 pc 0x6198c4 libart.so (art::ThreadPoolWorker::Callback(void*) + 160)
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

HeapTaskDaemon (waiting):tid=9 systid=24283 
#00 pc 0x4d5e0 libc.so (syscall + 32)
#01 pc 0x48771c libart.so (art::ConditionVariable::TimedWait(art::Thread*, long, int) + 252)
#02 pc 0x46cf20 libart.so (art::gc::TaskProcessor::GetTask(art::Thread*) + 196)
#03 pc 0x46ce10 libart.so (art::gc::TaskProcessor::RunAllTasks(art::Thread*) + 32)
       at dalvik.system.VMRuntime.runHeapTasks(Native method)
       at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:609)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

ReferenceQueueDaemon (waiting):tid=10 systid=24284 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:232)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

FinalizerWatchdogDaemon (timed waiting):tid=11 systid=24286 
       at java.lang.Thread.sleep(Native method)
       at java.lang.Thread.sleep(Thread.java:450)
       at java.lang.Thread.sleep(Thread.java:355)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:438)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForProgress(Daemons.java:480)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:369)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

Binder:24275_1 (native):tid=12 systid=24287 
#00 pc 0x9ece8 libc.so (__ioctl + 8)
#01 pc 0x5a890 libc.so (ioctl + 152)
#02 pc 0x45840 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 288)
#03 pc 0x45b18 libbinder.so (android::IPCThreadState::getAndExecuteCommand() + 24)
#04 pc 0x46410 libbinder.so (android::IPCThreadState::joinThreadPool(bool) + 68)
#05 pc 0x6c5a8 libbinder.so (android::PoolThread::threadLoop() + 380)
#06 pc 0x120a8 libutils.so (android::Thread::_threadLoop(void*) + 260)
#07 pc 0xbeecc libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*) + 144)
#08 pc 0x11960 libutils.so (thread_data_t::trampoline(thread_data_t const*) + 404)
#09 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#10 pc 0x5288c libc.so (__start_thread + 64)

Binder:24275_2 (native):tid=13 systid=24288 
#00 pc 0x9ece8 libc.so (__ioctl + 8)
#01 pc 0x5a890 libc.so (ioctl + 152)
#02 pc 0x45840 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 288)
#03 pc 0x45b18 libbinder.so (android::IPCThreadState::getAndExecuteCommand() + 24)
#04 pc 0x46410 libbinder.so (android::IPCThreadState::joinThreadPool(bool) + 68)
#05 pc 0x6c5a8 libbinder.so (android::PoolThread::threadLoop() + 380)
#06 pc 0x120a8 libutils.so (android::Thread::_threadLoop(void*) + 260)
#07 pc 0xbeecc libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*) + 144)
#08 pc 0x11960 libutils.so (thread_data_t::trampoline(thread_data_t const*) + 404)
#09 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#10 pc 0x5288c libc.so (__start_thread + 64)

FinalizerDaemon (waiting):tid=14 systid=24285 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:203)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:224)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)

Profile Saver (native):tid=15 systid=24289 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x47cc80 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 140)
#02 pc 0x543774 libart.so (art::ProfileSaver::Run() + 372)
#03 pc 0x538fc0 libart.so (art::ProfileSaver::RunProfileSaverThread(void*) + 148)
#04 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#05 pc 0x5288c libc.so (__start_thread + 64)

Crashlytics Exception Handler1 (waiting):tid=17 systid=24293 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:1012)

com.google.firebase.crashlytics.startup1 (waiting):tid=18 systid=24294 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:1012)

awaitEvenIfOnMainThread task continuation executor1 (waiting):tid=20 systid=24297 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:1012)

pool-6-thread-1 (waiting):tid=22 systid=24301 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

OkHttp ConnectionPool (timed waiting):tid=23 systid=24303 
       at java.lang.Object.wait(Native method)
       at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

WM.task-1 (waiting):tid=25 systid=24306 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

WM.task-2 (waiting):tid=26 systid=24308 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

Binder:24275_3 (native):tid=27 systid=24315 
#00 pc 0x9ece8 libc.so (__ioctl + 8)
#01 pc 0x5a890 libc.so (ioctl + 152)
#02 pc 0x45840 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 288)
#03 pc 0x45b18 libbinder.so (android::IPCThreadState::getAndExecuteCommand() + 24)
#04 pc 0x46410 libbinder.so (android::IPCThreadState::joinThreadPool(bool) + 68)
#05 pc 0x6c5a8 libbinder.so (android::PoolThread::threadLoop() + 380)
#06 pc 0x120a8 libutils.so (android::Thread::_threadLoop(void*) + 260)
#07 pc 0xbeecc libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*) + 144)
#08 pc 0x11960 libutils.so (thread_data_t::trampoline(thread_data_t const*) + 404)
#09 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#10 pc 0x5288c libc.so (__start_thread + 64)

RenderThread (native):tid=28 systid=24316 
#00 pc 0x9fca8 libc.so (__epoll_pwait + 8)
#01 pc 0x1663c libutils.so (android::Looper::pollInner(int) + 180)
#02 pc 0x16520 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 112)
#03 pc 0x64270c libhwui.so (android::uirenderer::ThreadBase::waitForWork() + 132)
#04 pc 0x64255c libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop() + 76)
#05 pc 0x120a8 libutils.so (android::Thread::_threadLoop(void*) + 260)
#06 pc 0x11960 libutils.so (thread_data_t::trampoline(thread_data_t const*) + 404)
#07 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#08 pc 0x5288c libc.so (__start_thread + 64)

flutter-worker-0 (timed waiting):tid=29 systid=24329 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:463)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:939)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

flutter-worker-1 (timed waiting):tid=30 systid=24330 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:463)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:939)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

com.it_nomads.fluttersecurestorage.worker (native):tid=31 systid=24344 
#00 pc 0x9fca8 libc.so (__epoll_pwait + 8)
#01 pc 0x1663c libutils.so (android::Looper::pollInner(int) + 180)
#02 pc 0x16520 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 112)
#03 pc 0x152c20 libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int) + 44)
       at android.os.MessageQueue.nativePollOnce(Native method)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

1.ui (native):tid=32 systid=24331 
#00 pc 0x9fca8 libc.so (__epoll_pwait + 8)
#01 pc 0x1663c libutils.so (android::Looper::pollInner(int) + 180)
#02 pc 0x16520 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 112)
#03 pc 0x17160 libandroid.so (ALooper_pollOnce + 100)
#04 pc 0x349764 libflutter.so 
#05 pc 0x347d8c libflutter.so 
#06 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#07 pc 0x5288c libc.so (__start_thread + 64)

queued-work-looper (native):tid=33 systid=24356 
#00 pc 0x9fca8 libc.so (__epoll_pwait + 8)
#01 pc 0x1663c libutils.so (android::Looper::pollInner(int) + 180)
#02 pc 0x16520 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 112)
#03 pc 0x152c20 libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int) + 44)
       at android.os.MessageQueue.nativePollOnce(Native method)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

Okio Watchdog (waiting):tid=34 systid=24383 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:313)
       at com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:42)
       at com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:288)

mali-mem-purge (unknown):tid=24318 systid=24318 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0x5ead4 libc.so (sem_wait + 132)
#03 pc 0x17d3f28 libGLES_mali.so (cmemp_hoard_purge_thread + 344)
#04 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#05 pc 0x5288c libc.so (__start_thread + 64)

mali-utility-wo (unknown):tid=24319 systid=24319 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0x5ead4 libc.so (sem_wait + 132)
#03 pc 0x17114b8 libGLES_mali.so (cmarp_utility_thread + 288)
#04 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#05 pc 0x5288c libc.so (__start_thread + 64)

mali-utility-wo (unknown):tid=24320 systid=24320 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0x5ead4 libc.so (sem_wait + 132)
#03 pc 0x17114b8 libGLES_mali.so (cmarp_utility_thread + 288)
#04 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#05 pc 0x5288c libc.so (__start_thread + 64)

mali-utility-wo (unknown):tid=24321 systid=24321 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0x5ead4 libc.so (sem_wait + 132)
#03 pc 0x17114b8 libGLES_mali.so (cmarp_utility_thread + 288)
#04 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#05 pc 0x5288c libc.so (__start_thread + 64)

mali-utility-wo (unknown):tid=24322 systid=24322 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0x5ead4 libc.so (sem_wait + 132)
#03 pc 0x17114b8 libGLES_mali.so (cmarp_utility_thread + 288)
#04 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#05 pc 0x5288c libc.so (__start_thread + 64)

mali-cmar-backe (unknown):tid=24323 systid=24323 
#00 pc 0x9fda8 libc.so (__ppoll + 8)
#01 pc 0x5cfb0 libc.so (poll + 92)
#02 pc 0x1711a3c libGLES_mali.so (cmarp_backend_thread + 588)
#03 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#04 pc 0x5288c libc.so (__start_thread + 64)

1.raster (unknown):tid=24332 systid=24332 
#00 pc 0x9fca8 libc.so (__epoll_pwait + 8)
#01 pc 0x1663c libutils.so (android::Looper::pollInner(int) + 180)
#02 pc 0x16520 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 112)
#03 pc 0x17160 libandroid.so (ALooper_pollOnce + 100)
#04 pc 0x349764 libflutter.so 
#05 pc 0x347d8c libflutter.so 
#06 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#07 pc 0x5288c libc.so (__start_thread + 64)

1.io (unknown):tid=24333 systid=24333 
#00 pc 0x9fca8 libc.so (__epoll_pwait + 8)
#01 pc 0x1663c libutils.so (android::Looper::pollInner(int) + 180)
#02 pc 0x16520 libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 112)
#03 pc 0x17160 libandroid.so (ALooper_pollOnce + 100)
#04 pc 0x349764 libflutter.so 
#05 pc 0x347d8c libflutter.so 
#06 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#07 pc 0x5288c libc.so (__start_thread + 64)

io.worker.1 (unknown):tid=24334 systid=24334 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb229c libc.so (pthread_cond_wait + 80)
#03 pc 0x334e78 libflutter.so 
#04 pc 0x343b98 libflutter.so 
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

io.worker.2 (unknown):tid=24335 systid=24335 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb229c libc.so (pthread_cond_wait + 80)
#03 pc 0x334e78 libflutter.so 
#04 pc 0x343b98 libflutter.so 
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

io.worker.3 (unknown):tid=24336 systid=24336 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb229c libc.so (pthread_cond_wait + 80)
#03 pc 0x334e78 libflutter.so 
#04 pc 0x343b98 libflutter.so 
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

io.worker.4 (unknown):tid=24337 systid=24337 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb229c libc.so (pthread_cond_wait + 80)
#03 pc 0x334e78 libflutter.so 
#04 pc 0x343b98 libflutter.so 
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

io.worker.5 (unknown):tid=24338 systid=24338 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb229c libc.so (pthread_cond_wait + 80)
#03 pc 0x334e78 libflutter.so 
#04 pc 0x343b98 libflutter.so 
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

io.worker.6 (unknown):tid=24339 systid=24339 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb229c libc.so (pthread_cond_wait + 80)
#03 pc 0x334e78 libflutter.so 
#04 pc 0x343b98 libflutter.so 
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

io.worker.7 (unknown):tid=24340 systid=24340 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb229c libc.so (pthread_cond_wait + 80)
#03 pc 0x334e78 libflutter.so 
#04 pc 0x343b98 libflutter.so 
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

io.worker.8 (unknown):tid=24341 systid=24341 
#00 pc 0x4d5dc libc.so (syscall + 28)
#01 pc 0x51e1c libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb229c libc.so (pthread_cond_wait + 80)
#03 pc 0x334e78 libflutter.so 
#04 pc 0x343b98 libflutter.so 
#05 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#06 pc 0x5288c libc.so (__start_thread + 64)

dart:io EventHa (unknown):tid=24342 systid=24342 
#00 pc 0x9fca8 libc.so (__epoll_pwait + 8)
#01 pc 0x62d49c libflutter.so 
#02 pc 0x661324 libflutter.so 
#03 pc 0xb3020 libc.so (__pthread_start(void*) + 264)
#04 pc 0x5288c libc.so (__start_thread + 64)

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
