### ISSUE TITLE
Still running on Flutter 3.7.0?

### ISSUE THREAD

**Issue by timobaehr** [mogol/flutter_secure_storage#514]
I upgraded to latest Flutter release 3.7.0 (before 3.3.10). Anyone here who also have problems after upgrade with this library?

```
flutter_secure_storage: ^7.0.1
```

AndroidManifest.xml
```xml
        <application
        ...
            android:fullBackupContent="@xml/backup_rules

        >
```

backup_rules.xml
```
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <exclude domain="sharedpref" path="FlutterSecureStorage"/>
</full-backup-content>
```

I'm seeing the following crash:
```
E/StorageCipher18Impl(19183): unwrap key failed
E/StorageCipher18Impl(19183): java.security.InvalidKeyException: Failed to unwrap key
E/StorageCipher18Impl(19183):     at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:792)
E/StorageCipher18Impl(19183):     at javax.crypto.Cipher.unwrap(Cipher.java:2441)
E/StorageCipher18Impl(19183):     at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.unwrap(RSACipher18Implementation.java:59)
E/StorageCipher18Impl(19183):     at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:39)
E/StorageCipher18Impl(19183):     at com.it_nomads.fluttersecurestorage.ciphers.StorageCipherAlgorithm$$ExternalSyntheticLambda0.apply(Unknown Source:2)
E/StorageCipher18Impl(19183):     at com.it_nomads.fluttersecurestorage.ciphers.StorageCipherFactory.getCurrentStorageCipher(StorageCipherFactory.java:84)
E/StorageCipher18Impl(19183):     at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.initStorageCipher(FlutterSecureStorage.java:167)
E/StorageCipher18Impl(19183):     at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.ensureInitialized(FlutterSecureStorage.java:141)
E/StorageCipher18Impl(19183):     at com.it_nomads.fluttersecurestorage.FlutterSecureStorage.containsKey(FlutterSecureStorage.java:54)
E/StorageCipher18Impl(19183):     at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:155)
E/StorageCipher18Impl(19183):     at android.os.Handler.handleCallback(Handler.java:942)
E/StorageCipher18Impl(19183):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/StorageCipher18Impl(19183):     at android.os.Looper.loopOnce(Looper.java:201)
E/StorageCipher18Impl(19183):     at android.os.Looper.loop(Looper.java:288)
E/StorageCipher18Impl(19183):     at android.os.HandlerThread.run(HandlerThread.java:67)
E/StorageCipher18Impl(19183): Caused by: javax.crypto.IllegalBlockSizeException
E/StorageCipher18Impl(19183):     at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:613)
E/StorageCipher18Impl(19183):     at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:790)
E/StorageCipher18Impl(19183):     ... 14 more
E/StorageCipher18Impl(19183): Caused by: android.security.KeyStoreException: Unknown error (internal Keystore code: -1000 message: In KeystoreOperation::finish
E/StorageCipher18Impl(19183): 
E/StorageCipher18Impl(19183): Caused by:
E/StorageCipher18Impl(19183):     0: In finish: KeyMint::finish failed.
E/StorageCipher18Impl(19183):     1: Error::Km(ErrorCode(-1000))) (public error code: 10 internal Keystore code: -1000)
E/StorageCipher18Impl(19183):     at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
E/StorageCipher18Impl(19183):     at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
E/StorageCipher18Impl(19183):     at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
E/StorageCipher18Impl(19183):     at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
E/StorageCipher18Impl(19183):     at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
E/StorageCipher18Impl(19183):     at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
E/StorageCipher18Impl(19183):     ... 15 more
```

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=JogvnnaJ8TI

**Comment by juliansteenbakker** [comment]
I am closing all older issues. If this issue still exists in the latest version, please let me know.
