### ISSUE TITLE
Android Devices throw error unless values are written as .toString()

### ISSUE THREAD

**Issue by SamuelMTDavies** [mogol/flutter_secure_storage#62]
I have run into what appears to be a bit of a Gotcha unless I am missing something.

I have a function that should securely store an email. 

**Android Devices Tested (Emulators):** 
Pixel Pie API 28
Pixel 2 XL Pie API 28
Pixel 3 XL Pie API 28
Nexus 6.0 Marshmallow API 23

These Android Devices throw the error below unless I write the value with .toString() as below.

`    await storage.write(key: 'email', value: email.toString());`

The function works perfectly  without .toString() for iOS devices and works fine with .toString().

Why is this? Should this be the expected behaviour as I feel it could catch plenty of people out.

**Function in question:**
```
  Future<void> persistLoginDetails({String email, String password}) async {
    /// // Create storage
    final storage = new FlutterSecureStorage();
    // Write value
    await storage.write(key: 'email', value: email);
    return;
  }
```

**Android Error:**

```
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): Failed to handle method call
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): java.lang.IllegalArgumentException: Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.onMethodCall(FlutterSecureStoragePlugin.java:92)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.it_nomads.com/flutter_secure_storage( 4489): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter ( 4489): PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference, null)
```

**Comment by z0mbie42** [comment]
I think your error come from that your are trying to put a `null` `email`.
You should assert that email is not null before writing it to secureStorage

**Comment by kurtiev** [comment]
Hello.
I also faced the same issue.
And need somehow store Map instead Strings, so guess the solution is to serialize only?

```
  Future<void> writeMap(Map<String, dynamic> data) {
    List<Future> futures = [];
    data.forEach((key, value) {
      // TODO Map type;
      futures.add(storage.write(key: key, value: value.toString()));
    });
    return Future.wait(futures);
  }
```

**Comment by juliansteenbakker** [comment]
Closing this because of no activity. Feel free to comment you think this shouldn't be closed.
