### ISSUE TITLE
PathAccessException: The process cannot access the file because it is being used by another process (Windows only) after breaking changes 9.0.0

### ISSUE THREAD

**Issue by stan-at-work** [mogol/flutter_secure_storage#634]
❗ 

After I updated to version 9.0.0, I randomly got an error saying: 'The process cannot access the file because it is being used by another process.'

This only happened after I upgraded to version 9.0.0.

I investigated the issue and came to the conclusion that it comes down to this.

If a file wants to read the same key at the same time as another file is writing to the same key, then I get this error.

I fixed this by switching back to the previous stable version.

I suggest updating the readme to alert users of this breaking issue.

This error also corrupts the .dat file, so all your secure storage is corrupted and unusable.

The error:

```
flutter: Failed to decrypt data: Error 0x00000057: Failure on CryptUnprotectData()
Delete corrupt file: c:\users\USER\appdata\roaming\com.example\APPNAME\flutter_secure_storage.dat
flutter: error on refresh token: PathAccessException: Cannot delete file, path = 'c:\users\USER\appdata\roaming\com.example\APPNAME\flutter_secure_storage.dat' (OS Error: The process cannot access the file because it is being used by another process.
flutter: , errno = 32) - stack: #0   _checkForErrorResponse (dart:io/common.dart:55:9)
flutter: #1   _File._delete.<anonymous closure> (dart:io/file_impl.dart:315:7)
flutter: #2   _rootRunUnary (dart:async/zone.dart:1407:47)
flutter: #3   _CustomZone.runUnary (dart:async/zone.dart:1308:19)
flutter: <asynchronous suspension>
flutter: #4   DpapiJsonFileMapStorage.load
flutter_secure_storage_windows_ffi.dart:267
flutter: <asynchronous suspension>
flutter: #5   FlutterSecureStorageWindows.write
flutter_secure_storage_windows_ffi.dart:142
flutter: <asynchronous suspension>
flutter: #6   CoreAuthRepo.toggleLoginEnvironmentInSecureStorage
core_auth_repo.dart:127
flutter: <asynchronous suspension>
flutter: #7   CoreAuthBloc._tryAutoLogin
core_auth_bloc.dart:113
flutter: <asynchronous suspension>
flutter: #8   Bloc.on.<anonymous closure>.handleEvent
bloc.dart:229
flutter: <asynchronous suspension>
flutter:
```

Greetings. Please fix ;-) 👍

**Comment by ReinRaus** [comment]
Code example: https://github.com/mogol/flutter_secure_storage/issues/603#issuecomment-1769261086

**Comment by stan-at-work** [comment]
@mogol

**Comment by KristijanMitrik** [comment]
Any updates on this issue @mogol ?

**Comment by stan-at-work** [comment]
> Any updates on this issue @mogol ?

You can use the previous version.

**Comment by xenSlayer** [comment]
any update on this issue?

**Comment by xenSlayer** [comment]
@stan-at-work which previous version are you using to avoid this issue?

**Comment by stan-at-work** [comment]
> @stan-at-work which previous version are you using to avoid this issue?

I'm using `flutter_secure_storage: ^8.1.0`

**Comment by rodrigoreal** [comment]
any update on this issue?

**Comment by stan-at-work** [comment]
Nope

**Comment by mikthemonster** [comment]
I have the same problem using flutter_secure_storage: ^9.2.2

**Comment by stan-at-work** [comment]
> I have the same problem using flutter_secure_storage: ^9.2.2

+ 1 i had the same error today after a long time of not having it again.

**Comment by stan-at-work** [comment]
@mogol  Any updates on this?

**Comment by stan-at-work** [comment]
@mogol ?

**Comment by juliansteenbakker** [comment]
Hi all, could you please check if this issue still exists with version v10.0.0-beta.1? Also, if this is still an issue, please provide a step by step guide on how to recreate this issue. Then i can look into it.

**Comment by durukan-iscan** [comment]
Hello @juliansteenbakker,

I have same Problem (only Windows) but i do not see "Windows OS Changes" in v10.0.0-beta.1 or v10.0.0-beta.2

**Comment by stan-at-work** [comment]
> v10.0.0-beta.1 does have changes for windows, however they are more related to the win32 implementation in flutter, and not about this problem i can see. I am going to look into this issue.

**Hey,**

I’m experiencing the same issue—it still persists.  

There’s no specific pattern that I can recreate. It happens about once a day. I’ve noticed it tends to occur more often when in release mode.  

I suspect it might be a race condition issue, possibly with locks not waiting for each other or something similar. But I’m not an expert. 😊

**Comment by nini22P** [comment]
Add multi storage file. It won't save a file at the same time.

**Comment by stan-at-work** [comment]
> ⚠️ This issue has been marked as **stale** because it has been open for **60 days** with no activity.
> 
> If this issue is still relevant, please comment to keep it active. Otherwise, it will be closed in **60 days**.

Still verry relevant

**Comment by stan-at-work** [comment]
> ⚠️ This issue has been marked as **stale** because it has been open for **60 days** with no activity.
> 
> If this issue is still relevant, please comment to keep it active. Otherwise, it will be closed in **60 days**.

Still verry relevant 🦖

**Comment by saikyun** [comment]
I had this issue. Turns out I didn't await properly and had read/writes trampling over each other.
I added this rule to my linter options (`analysis_options.yaml`), and added `await` everywhere that I had missed it. Now it works as expected. :)

```
linter:
  rules:
    - unawaited_futures
```

**Comment by stan-at-work** [comment]
Still very relevant 🦖

**Comment by juliansteenbakker** [comment]
This issue has been stale for a while, but i've setup a good windows test environment which i didn't have, so i will be looking into this the next few days.
