### ISSUE TITLE
EncryptedSharedPreferences initialization failed - anomaly 

### ISSUE THREAD

**Issue by qwadrox** [mogol/flutter_secure_storage#651]
A the problem only occurred on certain devices.
Only after release, and only on one flavor.  

```java
EncryptedSharedPreferences initialization failed
javax.crypto.AEADBadTagException
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:611)
	at javax.crypto.Cipher.doFinal(Cipher.java:2114)
	at z8.b.c(Unknown Source:27)
	at z8.b.b(Unknown Source:5)
	at s8.n.c(Unknown Source:8)
	at s8.n.o(Unknown Source:7)
	at s8.n.n(Unknown Source:3)
	at z8.a$b.j(Unknown Source:19)
	at z8.a$b.f(Unknown Source:50)
	at f2.a.b(Unknown Source:50)
	at f2.a.a(Unknown Source:4)
	at uc.a.j(Unknown Source:57)
	at uc.a.f(Unknown Source:101)
	at uc.a.b(Unknown Source:0)
	at uc.e$b.run(Unknown Source:222)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.security.KeyStoreException: Signature/MAC verification failed
	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:356)
	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
	at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:127)
	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
	at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
	at javax.crypto.Cipher.doFinal(Cipher.java:2114) 
	at z8.b.c(Unknown Source:27) 
	at z8.b.b(Unknown Source:5) 
	at s8.n.c(Unknown Source:8) 
	at s8.n.o(Unknown Source:7) 
	at s8.n.n(Unknown Source:3) 
	at z8.a$b.j(Unknown Source:19) 
	at z8.a$b.f(Unknown Source:50) 
	at f2.a.b(Unknown Source:50) 
	at f2.a.a(Unknown Source:4) 
	at uc.a.j(Unknown Source:57) 
	at uc.a.f(Unknown Source:101) 
	at uc.a.b(Unknown Source:0) 
	at uc.e$b.run(Unknown Source:222) 
	at android.os.Handler.handleCallback(Handler.java:938) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loopOnce(Looper.java:210) 
	at android.os.Looper.loop(Looper.java:299) 
	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by qwadrox** [comment]
Clearing datas and cache of the app indeed solves the problem.
I hope this helps. 

[https://stackoverflow.com/a/71764131/11627846](https://stackoverflow.com/a/71764131/11627846)
