### ISSUE TITLE
Error while reading data on windows

### ISSUE THREAD

**Issue by Lampadina17** [mogol/flutter_secure_storage#757]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:50:27)
<asynchronous suspension>
```

**Comment by Lampadina17** [comment]
to solve this error is necessary to import even the extensions such as

- flutter_secure_storage_linux
- flutter_secure_storage_macos
- flutter_secure_storage_windows
