### ISSUE TITLE
Error App crash on start

### ISSUE THREAD

**Issue by jonataslaw** [mogol/flutter_secure_storage#81]
The plugin works normal on my physical device with android 8.1.
However, plugin causes Android 4.4 emulator crash

I did some more testing, and the plugin works well on all API 23+
However, it crashes on android 4.4 and 4.3 with the error below

com/it_nomads/fluttersecurestorage/ciphers/RSACipher18Implementation
        at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
        at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.<init>(FlutterSecureStoragePlugin.java:46)
        at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(FlutterSecureStoragePlugin.java:33)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:31)
        at com.app.contatinhos.MainActivity.onCreate(MainActivity.java:11)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)

Step to reproduce:

final storage = new FlutterSecureStorage();
String s = await storage.read(key: "protect");

**Comment by jyp334** [comment]
I had the same problem.Have you solved the problem?

**Comment by awafL** [comment]
There is a statement made in the flutter_secure_storage package page that says:

> Note KeyStore was introduced in Android 4.3 (API level 18). The plugin wouldn't work for earlier versions.

There might reside the problem that you are facing when using android 4.3.

I can't explain why it would not work in android 4.4, but since it has not that many changes in structure from the api 18 to 19, i woud recommend to develop in earlier versions. Android 4 is obsolete at this point: https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide

**Comment by juliansteenbakker** [comment]
Please try again with latest dev branch. I'm closing this for now due to no activity.
