### ISSUE TITLE
reading nonexistent key fails on some devices (Android)

### ISSUE THREAD

**Issue by peter-meemo** [mogol/flutter_secure_storage#84]
On a physical Moto G6, I see the following error when trying to read a nonexistent key (or call readAll):

```
I/flutter (25299): 12:43:12.630 | SEVERE - PlatformException(error, Unsupported value: javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, null)
I/flutter (25299): 12:43:12.634 | SEVERE - #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (25299): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
I/flutter (25299): <asynchronous suspension>
I/flutter (25299): #2      FlutterSecureStorage.readAll (package:flutter_secure_storage/flutter_secure_storage.dart:48:40)
```

**Comment by lovung** [comment]
I got same issue on Oppo.

**Comment by VadimOsovsky** [comment]
I got the same in release mode, in debug mode seems to work fine

**Comment by LOG-TAG** [comment]
Same on Samsung galaxy J7

**Comment by rignaneseleo** [comment]
any fix?

**Comment by peter-meemo** [comment]
You can catch the PlatformException and check it, that's the only workaround I know of.

**Comment by morrica** [comment]
Same on Pixel 3 in Release mode. Works fine in Debug mode.

**Comment by juliansteenbakker** [comment]
This is expected behavior. It's throwing an exception because it can't decrypt it because of a wrong key. That's why it's saying BAD_DECRYPT.

**Comment by stevenspiel** [comment]
Why is the key wrong?

**Comment by ray007** [comment]
I'm now getting a quite similar error on my Pixel-6:
```
PlatformException(Exception encountered, readAll, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2074)
	at N0.a.b(SourceFile:50)
	at N0.a.h(SourceFile:104)
	at N0.d.run(SourceFile:273)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```
Funny thing: it always happened so far when I tried the normal release route, I once tries with "internal app sharing", and the error didn't occur then.

Should I open a new issue?

**Comment by astheras** [comment]
try to remove old and install new version of your app. Did you install(for example) release over debug or debug over release app version? I had the same issue when I ran debug, when I had release installed
